### ISSUE TITLE
Criar um site exibindo as questões do forum

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#1]

**Comment by woliveiras** [comment]
Da pra criar uma página simples ou mesmo uma SPA pra listar isso usando a API do GitHub:

[API V3 /issues](https://developer.github.com/v3/issues/)

Ex.: 

```
curl -X GET https://api.github.com/repos/backend-br/forum/issues -o response.txt
```

Resultado

[response.txt](https://github.com/backend-br/forum/files/1309053/response.txt)

**Comment by diegocosta** [comment]
@reginaldojunior @woliveiras Quer colocar isso no site?

**Comment by khaueviana** [comment]
Acho bacana @diegocosta!

**Comment by reginaldojunior** [comment]
Acho uma boa para aumentar o SEO do site e aumentar a visibilidade da comunidade...
