### ISSUE TITLE
Node.Js ou PHP ?

### ISSUE THREAD

**Issue by anax4** [backend-br/forum#100]
Olá galera, sou iniciante e atualmente tenho experiência jr com php, surgiu uma oportunidade de estágio para mergulhar no node.js.
Qual skill vale mais a pena ter a experiência hoje em dia?

**Comment by lucasmahle** [comment]
Ambas oportunidades eu julgo boas. Por ser jr, tu tem um caminho muito bom pra aprender, então indiferente da escolha, tu vai colher bons frutos. Se quiseres se aventurar no node, vai la, mas se quiseres continuar no PHP, também é uma boa opção. Se tu mora em uma cidade grande, ai eu acho que o peso da decisão é menor ainda, pqe vaga vai ter kk

**Comment by Vagnerlg** [comment]
Na minha opinião vale sempre olhar pra vagas na sua região, eu quando comecei, pesquisei as vagas de dev e vendo o que mais aparecia, quanto quem é melhor ou pior, não vejo como um discussão viável

**Comment by jeancsanchez** [comment]
Acho que no começo da carreira vale aprender e ter o contato com o máximo de tecnologias possíveis. Isso vai fazer muita diferença quando você estiver tomando decisões como um senior ou como um líder de algum projeto. Mas fica aqui um conselho: não se apegue tanto às linguagens em si. Se atente em aprender os conceitos por trás delas, os paradigmas e etc.
