### ISSUE TITLE
Algorítmo para Performance de Back-End

### ISSUE THREAD

**Issue by henriquegibi** [backend-br/forum#101]
Salve salve, tudo bem?
Espero que sim!

Eu tenho uma dúvida técnica. Interrompi meu curso de Java para fazer um curso específico de algorítmos porque senti a necessidade, e em uma determinada aula, eu percebi que eu consegui a mesmíssima solução que o professor, porém com um código bem diferente,

Entendo que o código dele está mais limpo e mais bem escrito que o meu, e se fôssemos comparar rodando cada código uma única vez no PC, não daria pra medir a diferença no cronômetro, mas se fosse uma aplicação back-end com 50 mil processamentos por dia, a coisa seria muito diferente que eu sei. Eu só não entendo o porquê.

O código do professor está [aqui](https://github.com/acenelio/curso-algoritmos/blob/master/visualg/par_impar.alg).
O meu código está [aqui](https://github.com/henriquegibi/algoritimos-iniciais/blob/master/Estrutura%20de%20repeti%C3%A7%C3%A3o/13%20-%20problema%20par%20impar.ALG).

Eu gostaria que alguém me explicasse ou me desse dicas do que estudar para entender a diferença no processamento de ambos códigos, apesar do mesmíssimo resultado. A título de gambiarra de emergência, serviria, mas isto não faria de mim um programador profissional.

Desde já, meu muito obrigado,
Henrique

**Comment by reginaldojunior** [comment]
Fala @henriquegibi blz?

Mano em computação existe uma notação que chamamos de BIG(O) ele serve para que mensuremos a capacidade de processamento de um algoritmo.

https://dev.to/danielle8farias/complexidade-de-algoritmos-notacao-big-o-26al

É bem complicado de entender, mas ela é bem útil para a compressão destes algoritmos.

Uma outra dica que dou é ler o livro "Entendendo algoritmos, Adiya Y. Bhargava"

**Comment by henriquegibi** [comment]
@reginaldojunior obrigado, de verdade, amanhã cedo eu vou ver este link com calma! 👍

**Comment by neiesc** [comment]
@henriquegibi esse cheat sheet é muito bom tbm https://www.bigocheatsheet.com/
