### ISSUE TITLE
Mover issues para discussions

### ISSUE THREAD

**Issue by rhuangabrielsantos** [backend-br/forum#104]
O que acham de fazer essa mudança neste repositório, até me coloco a disposição para ajudar se precisarem ^^

Bora levantar essa comunidade ♥️

**Comment by reginaldojunior** [comment]
Esse discussions fica aqui no github mesmo? Como que seria essa transferencia tem algum caso que ja utiliza assim para vermos exemplos?

**Comment by rhuangabrielsantos** [comment]
Fica sim! Um exemplo muito bom é a comunidade frontendbr/forum que era issue e mudaram pra essa nova funcionalidade do github.

Link: https://github.com/frontendbr/forum

**Comment by reginaldojunior** [comment]
Poxa que massa, tava dando uma pesquisada aqui. É só ativar nas preferencias do repositório né?

**Comment by reginaldojunior** [comment]
Achei aqui onde configura, massa tem umas coisas, uns textos e explicações que tem que colocar. Não consigo fazer agora mas achei legal a ideia.

**Comment by reginaldojunior** [comment]
https://github.com/backend-br/forum/discussions

**Comment by rhuangabrielsantos** [comment]
Isso ae, 

É interessante também criar a configuração da impedir a criação de novas issues, que também tem um exemplo nesse repositório aí.

Se precisar de ajuda ou se eu conseguir ajudar em algo, manda mensagem lá no discord RhN#1271

**Comment by reginaldojunior** [comment]
Acho que tem que atualizar o readme, outras e ver como passar as issues para lá, continuo depois. Vlw @rhuangabrielsantos qualquer coisa de dou um alo la no Discord
