### ISSUE TITLE
Votação icone/logo comunidade.

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#11]
O nosso colaborador @diegocosta fez este icone/logo para gente.

![backendbr-logo](https://user-images.githubusercontent.com/7466894/29522975-a9ca8cba-8661-11e7-8cab-19d2057ce74d.png)

O que vocês acham? Alguma sugestão?

**Comment by felipejsm** [comment]
Eu achei muito bom o/

**Comment by richmanzoli** [comment]
Foda, curti muito :)

**Comment by nicholasess** [comment]
Eu gostei bastante e pedi algumas sugestões para os designers da empresa:
- Tirar o BR do nome, já que a bandeira do Brasil simboliza essa informação.
- Tirar o icone do github e a bandeirinha, já que ao diminuir elas não ficarão nítidas.
- As baias do gabinete poderiam ser somente uma, muitas não representou bem isso.

E gerar um icone menor pra ser algo solto que possa ser impresso ou virar sticker.

**Comment by reginaldojunior** [comment]
@nicholasess ótimo!  @diegocosta você consegue fazer isso? Se preferir pode passar o editável que a gente faz as modificações...

**Comment by diegocosta** [comment]
Taí as modificações seguridas. 
![backendbr](https://user-images.githubusercontent.com/3134422/29620720-158b9072-87f5-11e7-9e5b-3afae6e83fcd.png)

Sobre as baias do gabinete a inspiração foi um gabinete para servidor:
![image](https://user-images.githubusercontent.com/3134422/29620784-474aa850-87f5-11e7-936c-b91872d3c399.png)

**Comment by raulfernando** [comment]
Acho que a baias representou bem oq era kkk sem elas ficou estranho.

Acho que seria legal ter umas engrenagem naquela tela abaixo da cpu (Engrenagem representa bem o Backend)

**Comment by nicholasess** [comment]
Mas a intenção do logo não representar todas as particularidades do back end, lembrando que elementos pequenos não são visíveis quando a logo ficar menor.

**Comment by khaueviana** [comment]
O último envio do @diegocosta ficou show!

**Comment by woliveiras** [comment]
Galera, como o logo já foi definido, não seria legal fechar essa issue?

**Comment by khaueviana** [comment]
Feito @woliveiras!
