### ISSUE TITLE
Enquete locais dos desenvolvedores

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#12]
Olá gostaria de saber como está distribuido aqui o pessoal, falem a localidade de vocês ai nos comentários. Afinal somos a comunidade BackEnd BR precisamos alcançar o Brasil inteiro.

**Comment by richmanzoli** [comment]
São Paulo - SP, Zona Leste.

**Comment by reginaldojunior** [comment]
Guarulhos - SP.

**Comment by diegocosta** [comment]
Salvador - BA.

**Comment by thiamsantos** [comment]
Florianópolis - SC.

**Comment by fredmosc** [comment]
Foz do Iguaçu - PR

**Comment by kivervinicius** [comment]
Tangará da Serra - MT

**Comment by felipejsm** [comment]
São Paulo - SP , Zona Sul

**Comment by Pedro-Souza** [comment]
Goiânia

**Comment by iamPedroVictor** [comment]
Manaus - AM

**Comment by raulfernando** [comment]
Guarulhos-SP

**Comment by gspaiva** [comment]
Lavras - MG

**Comment by Vitor-Felipe** [comment]
Uberaba - MG

**Comment by houstondapaz** [comment]
São Paulo - SP

**Comment by nicholasess** [comment]
Praia Grande - SP/Litoral

**Comment by rpaggi** [comment]
Barueri - SP

**Comment by khaueviana** [comment]
São Paulo - SP

**Comment by jmurowaniecki** [comment]
Porto Alegre - RS

**Comment by yanmagale** [comment]
Belo Horizonte - MG

**Comment by oPauloChaves** [comment]
Teresina - PI

**Comment by mdamaceno** [comment]
Juiz de Fora - MG

**Comment by gucastiliao** [comment]
São Paulo - SP, Zona Leste.

**Comment by ericOnda** [comment]
Currais Novos - Rio Grande do Norte

**Comment by Marlysson** [comment]
Teresina - Piauí

**Comment by AlbericoD** [comment]
Americana - SP

**Comment by aicoutos** [comment]
Ijuí - RS

**Comment by weltonsanches** [comment]
Ivaiporã - PR

**Comment by nataliawinter** [comment]
Porto Alegre - RS

**Comment by lucasprag** [comment]
São Paulo - SP

**Comment by rafa-acioly** [comment]
Arujá - SP

**Comment by mstuttgart** [comment]
São Paulo - SP

**Comment by jonathas** [comment]
do Rio de Janeiro, RJ, mas morando desde 2015 em Brno, República Tcheca

**Comment by jass2125** [comment]
João Pessoa -PB

**Comment by Cleysonlb** [comment]
@reginaldojunior poderia fazer um google form pra você conseguir metrificar isso de forma mais efetiva 👍

**Comment by reginaldojunior** [comment]
@Cleysonlb farei isso, estamos modificando algumas coisas na organização e já faço isso junto. :dancer: :+1:

**Comment by Cleysonlb** [comment]
mas respondendo a enquete 💃  sou de Teresópolis - RJ
