### ISSUE TITLE
Divulgação de Cursos

### ISSUE THREAD

**Issue by felipejsm** [backend-br/forum#14]
Tudo beleza, pessoal?
Tá rolando uma promoção na [Udemy](https://www.udemy.com/), vários cursos(ou todos?) por R$20,00 até 31/08

o/

**Comment by diegocosta** [comment]
São alguns :( Alguns publishers podem escolher não participar de promoções.
Já garanti de Docker e Kotlin

**Comment by khaueviana** [comment]
Mudei para "Divulgação de Cursos", pra galera divulgar cursos pra rapaziada!

**Comment by khaueviana** [comment]
Duplicado!
