### ISSUE TITLE
JWT + JAVA EE

### ISSUE THREAD

**Issue by kivervinicius** [backend-br/forum#16]
E ai galera, alguém utiliza alguma implementação de JWT com JAVA 6? Já baixei diversas libs (auth0, jjwt, jose) e todas elas exigem que seja JAVA 7+. Há alguma idéia em como fazer a codificação de um payload de forma manual?

**Comment by kivervinicius** [comment]
Como não consegui nada, acabei criando uma pequena classe caso conhecedores do Java possam contribuir, até o momento tem me servido bem.

https://github.com/OmegaSistemas/SimpleJWT

**Comment by Marlysson** [comment]
Tem essa lib que diz ser compatível:

https://connect2id.com/blog/jwt-with-java-6

Massa tua lib, uma curiosidade.. usou todos métodos estáticos para simplificar utilizar sem instâncias, diretamente logo.

**Comment by kivervinicius** [comment]
@Marlysson fiz ela bem simples somente para resolver este problema em especifico, preferi trabalhar com static por ser mais rápida a utilização, referente a lib que você mencionou eu teste mas não funcionou pois precisou de muitas dependências, como nesse primeiro momento só precisava fazer o encode foi mais rápido.
