### ISSUE TITLE
Eventos e Palestras

### ISSUE THREAD

**Issue by khaueviana** [backend-br/forum#17]
Divulguem os eventos e palestras que estão rolando na comunidade.

**Comment by jmurowaniecki** [comment]
Evento|Data|Local|Média de Valores|Possibilidade de desconto
---|---:|:---:|:---:|:---:
[PHP TestFest Setup](https://www.meetup.com/pt-BR/PHP-RS/)|14 de Setembro|Sede Umbler (Gravataí)|free|_Se organizar rola carona._
[RoadSec PoA](https://www.eventbrite.com/e/roadsec-2017-porto-alegre-registration-30533541645?aff=contatosite)|30 de Setembro|Faculdade Dom Bosco (PoA)|$50~$150|Sim
[TDC PoA](http://www.thedevelopersconference.com.br/tdc/2017/index.html)|8 à 11 de Novembro|?|$50~$400|Sim

**Comment by khaueviana** [comment]
Duplicado com o repo de eventos :)
