### ISSUE TITLE
[PHP] - Problemas ao capturar o JSON enviado de um post.

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#18]
Pessoal, 

Alguém já teve um problema com captura de informações vindas de um post com PHP, no meu caso estou usando o file_get_contents é um plugin em opencart e ele sempre retorna null, mas em outros clientes funciona ok, só em um especifico não funciona, sabe se pode ser alguma configuração e se for, qual?

```
$json = file_get_contents("php://input");

//convert the string of data to an array
$data = json_decode($json, true);

//output the array in the response of the curl request
print_r($data);
```

Já tentei algumas coisas do stackoverflow e nada ainda.

**Comment by aicoutos** [comment]
tenta $_POST['input'] ao invés de php://input.
