### ISSUE TITLE
Linguagens de programação funcional

### ISSUE THREAD

**Issue by khaueviana** [backend-br/forum#19]
Pessoal,

Vocês estão brincando com programação funcional? Se sim, quais linguagens e tecnologias estão utilizando?

**Comment by deyvisonrocha** [comment]
Então, um amigo meu tá trabalhando muito com Elixir. Tenho vontade, mas não vejo muitas vagas.

**Comment by khaueviana** [comment]
É verdade, tenho visto Elixir tbm, acho que em relação as vagas, só mais pro futuro mesmo!

**Comment by guilhermejcgois** [comment]
Já brinquei com [Haskell](https://www.haskell.org/) por hobby, nada sério. No trampo uso javascript, dá para fazer umas coisas bem legais, no meu caso front, porém tem NodeJS pra brincar no back

**Comment by woliveiras** [comment]
No Brasil encontramos poucas oportunidades de emprego com linguagens puramente funcionais ou que tenham seu escopo maior no paradigma, mas muita gente procura devs que conheçam bem sobre o assunto por que utilizam libs para trabalhar de maneira funcional em suas stacks. Seja em JavaScript, Python, Ruby, etc.

Algumas empresas daqui estão utilizando, por ordem de mais utilizadas (pelo que eu vi):

1. Scala
1. Elixir
1. Clojure

Mas eu não encontrei nenhuma usando Haskell, por exemplo (:cry:).

Elixir permanece uma linguagem em constante crescimento de adoção e muita gente se envolvendo na comunidade. É uma comunidade bem mais ativa do que a de Clojure, mas, **acho** que, não tão ativa quanto a de Scala.

Eu comecei a estudar o conceito mais a fundo esse ano e estou fazendo o curso (gratuito) do professor Marcos Castro na Udemy: [Haskell para Iniciantes](https://www.udemy.com/curso-haskell/). Estou curtindo bastante!

Se vocês buscam aprender pra tentar trampo com essas linguagens, eu recomendo fortemente que comecem logo a estudar e criar uns projetos! Não deixem de estudar só por que não tem muita vaga no Brasil. Afinal o trampo remoto está ai pra nos ajudar, galera. :raised_hands: :raised_hands: :raised_hands: 

Nas últimas três semanas eu estou estudando Clojure por que me indicaram um livro muito legal, [BRAVE CLOJURE - BECOME A BETTER PROGRAMMER](braveclojure.com), e estou gostando bastante.

Porém existe outro livro fera também que é para Haskell: [Learn You a Haskell for a great job](http://learnyouahaskell.com/). Que também recomendo pra quem quiser se envolver no Haskell.

Por enquanto eu continuo estudando Clojure e Haskell e depois pretendo me aprofundar na pratica com alguma linguagem ou usar uma lib ([Ramda](http://ramdajs.com/)) pra trabalhar com o paradigma no JavaScript.

**Comment by khaueviana** [comment]
boa @woliveiras!!!!

**Comment by thiamsantos** [comment]
O mercado de Scala é promissor? Hoje em dia eu trabalho com node e php, mas estou pensando em migrar para o scala. Alguém tem alguma sugestão ou dica quanto a isso?

**Comment by oPauloChaves** [comment]
Venho estudando bastante Elixir/Erlang e tenho gostado muito. Fiz este curso [The Complete Elixir and Phoenix Bootcamp](https://www.udemy.com/the-complete-elixir-and-phoenix-bootcamp-and-tutorial/) na Udemy do Stephen Grider e achei bem legal. Tô me aprofundando cada vez mais, fazendo projetos pessoais pois quero pegar trampo onde eu possa aplicar este conhecimento.
