### ISSUE TITLE
Recomendação de projeto open source

### ISSUE THREAD

**Issue by gmmoraes** [backend-br/forum#20]
Boa noite!

Eu queria saber se alguem da #backend-br teria algum um projeto open source que use a framework express.js para recomendar?

Abraços!

**Comment by khaueviana** [comment]
Opa @gmmoraes dá uma olhada nessa lista, pode ajudar 😄 

https://github.com/MunGell/awesome-for-beginners

**Comment by onhernandes** [comment]
Ainda tô aprimorando hahaha, mas já dá pra usar o básico. É uma API pra download de vídeos do YT em MP3, por enquanto suporta apenas POST.

https://github.com/onhernandes/soundman

**Comment by gmmoraes** [comment]
@onhernandes, bem interessante o seu projeto!

Você gostaria de alguma ajuda?

**Comment by onhernandes** [comment]
@gmmoraes quero sim! A noite vou colocar o que falta pro projeto ficar pronto nas issues, se quiser pegar uma mais tarde e ajudar eu agradeço!

**Comment by JoseCage** [comment]
Aproveitando a deixa, @gmmoraes  estou precisando ajuda com o frontend (que ainda nem existe infelizmente) do meu projeto [doesangue.me](https://github.com/doesangueorg/doesangue-core).

A estrutura do **core** é uma API. A ideia é depois fazer um app mobile, um spa e deixar outras pessoas/projetos consumir nossos dados..

**Comment by reginaldojunior** [comment]
@JoseCage belo projeto!!! ❤️  Vou tentar ajudar assim que possivel...

**Comment by JoseCage** [comment]
> @JoseCage belo projeto!!!  Vou tentar ajudar assim que possivel...

Opa.. Valeu irmão..

**Comment by gmmoraes** [comment]
@onhernandes Show de bola, hj de noite eu dou uma checada lá na pagina do projeto pra ver como eu posso ajudar.

@JoseCage Bem legal o seu projeto tbm!
No final de semana eu vou dar uma olhada na pagina do projeto pra ver se pego um issue pra trabalhar.

**Comment by JoseCage** [comment]
> @JoseCage Bem legal o seu projeto tbm!
> No final de semana eu vou dar uma olhada na pagina do projeto pra ver se pego um issue pra trabalhar.

Qualquer dúvida pode abrir lá uma issue ou mesmo falar comigo por e-mail se quiser: _jose.cage@doesangue.me_

**Comment by gmmoraes** [comment]
@JoseCage Poder deixar!

**Comment by reginaldojunior** [comment]
Ae pessoal, um repositório novo para quem quiser dar uma olhada...

https://github.com/ciawn/deploy

:smile:
