### ISSUE TITLE
Back-end - Engineer/Analista/Junior/Pleno/etc

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#21]
Como vocês definem cada um, quais conhecimentos precisa ter e etc? Já ouvi que Estagiário vai até 1 ano, Junior de 2 a 5 e por ai vai, mas em relação a conhecimentos, como vocês definem?

**Comment by diegocosta** [comment]
Eu gosto bastante desse repositório sobre carreira: https://github.com/abraphp/CarreiraPHP
Apesar de focar em PHP, dá pra aplicar em outras linguagens.

**Comment by khaueviana** [comment]
Essa é uma grande questão do nosso mercado, o que gosto de fazer é olhar algumas referências das áreas, ler seus livros, e acompanhar caras melhores do que eu. Acho que com isso, você consegue se avaliar, onde você está e pra onde vai. 

Você pode seguir um livro de receitas e tal, mas são muitas variáveis em jogo, que não incluem apenas habilidades técnicas!

**Comment by khaueviana** [comment]
Uma ref.: http://www.vagas.com.br/profissoes/acontece/no-mercado/voce-e-junior-pleno-ou-senior/

**Comment by onhernandes** [comment]
Valeu galera :)

**Comment by woliveiras** [comment]
A dica do @diegocosta é muito boa! Esse repo é show!

Algo que também pode acontecer é você se sentir em nível pleno/senior e quando chega na entrevista a empresa te dizer que você foi avaliado como junior (no caso do pleno) ou pleno (pro caso do senior) e isso é extremamente normal.

Não existe uma regra escrita em pedra que todas as empresas seguem para avaliar seus profissionais e por isso temos até empresas com cargos junior I, junior II, junior II, aí vida pleno I, pleno II, pleno III. Fora isso ainda tem empresas que fazem um fluxo de estagiário(a) -> assistente -> junior -> pleno -> senior, aumentando ainda mais a quantidade de níveis a se alcançar.

Não encane tanto com títulos, eles não dizem muita coisa.

Já vi plenos com mais responsabilidade que seniores e seniores com menos conhecimento técnico do que plenos. Acontece.

Procure sempre estudar/praticar e se manter atualizado e quando tiver oportunidade peça uma promoção.

Outra coisa: procure analisar as vagas de emprego que estão a um nível acima de você e sempre busque aprender essas coisas. Não tudo, claro, por que existem vagas absurdas.

**Comment by khaueviana** [comment]
> "Já vi plenos com mais responsabilidade que seniores e seniores com menos conhecimento técnico do que plenos. Acontece."

 - umas das poucas verdades da nossa área hehe

**Comment by dadario** [comment]
A Basecamp tem no seu handbook uma descrição sobre níveis de programadores: https://github.com/basecamp/handbook/blob/master/titles-for-programmers.md
