### ISSUE TITLE
Aumentar o alcance e visibilidade do forum

### ISSUE THREAD

**Issue by woliveiras** [backend-br/forum#22]
Conforme dito na issue https://github.com/backend-br/forum/issues/12, o objetivo do forum é alcançar o Brasil inteiro.

Visando isso, seria necessário criar alguma estratégia de crescimento para o projeto.

É necessário ter planos para administração e moderação do forum, assim como esquemas de divulgação.

Seria interessante existir:

- uma conta no Twitter como backendbr, onde seriam postadas as novidades da comunidade
- uma conta no Twitter (com um bot, talvez) postando as issues criadas aqui nos repositórios
- uma página no Facebook
- mais conteúdo no site oficial, pra que ele seja melhor indexado pelo Google
- parcerias de divulgação

**Comment by woliveiras** [comment]
No [Training Center](https://github.com/training-center/) já fazemos um trabalho de divulgar as comunidades de desenvolvimento, eventos, cursos, etc. Então é uma parceria sem aviso prévio (:joy:), mas seria muito legal conseguir o apoio de outras comunidades.

**Comment by khaueviana** [comment]
Bacana @woliveiras!

Acho que podemos criar um backlog pra atividades nesse sentido, aqui na organização, e colocar responsáveis.

@reginaldojunior e @diegocosta, o que acharam dessas ideias?

**Comment by khaueviana** [comment]
Posso ficar responsável pelo Twitter (minha rede predileta) :D

**Comment by diegocosta** [comment]
@khaueviana @woliveiras Acho válido!

@khaueviana Pega o twitter rs!

**Comment by Pedro-Souza** [comment]
@khaueviana Já foi criado o twitter?

**Comment by reginaldojunior** [comment]
@Pedro-Souza criamos 😄 

https://twitter.com/BackendBrasil

**Comment by Pedro-Souza** [comment]
Boa! Já estou seguindo!

**Comment by reginaldojunior** [comment]
@woliveiras 

Bot criado :+1: 

https://github.com/backend-br/bot-twitter

E rodando a cada 2 horas... Vou seguir com as outras dicas agora.

**Comment by khaueviana** [comment]
Da hora manoooo

**Comment by reginaldojunior** [comment]
O que acham desta imagem para tentamos enviar alguns emails para umas empresas, escolas de desenvolvimento e etc... para tentamos descontos, espaços para palestras e etc...

![mkt-backend-br](https://user-images.githubusercontent.com/7466894/31047473-c3b575f0-a5e1-11e7-9077-19bf5985c6c5.jpg)

**Comment by khaueviana** [comment]
Ficou legal mano, segue uma sugestão de texto, acho que ficou muito grande. E galera não lê texto grande hahah

"Uma comunidade de desenvolvimento voltada ao backend, com a missão de agregar conhecimento, conteúdo e informação para todos os desenvolvedores. Tudo isso de maneira colaborativa, e com ajuda de todos. 

Estamos procurando empresas parceiras para postar vagas e que possam ajudar a comunidade na divulgação, com espaço para eventos, descontos para cursos e tudo que possa ajudar os backenders \o"
