### ISSUE TITLE
Stack de desenvolvimento Back-End

### ISSUE THREAD

**Issue by khaueviana** [backend-br/forum#24]
E ai povo,

Qual stack de desenvolvimento vocês estão utilizando no dia-a-dia? 

Linguagem, IDE, BD, Front-end, Ferramenta de Automatização, Repositório, Gestão do Projeto e por ai vai....

**Comment by Pedro-Souza** [comment]
No serviço usamos c# e mysql, ionic e firebase.
E git para controle

**Comment by reginaldojunior** [comment]
No trabalho:

 - PHP (Laravel), MySQL, Apache, ElasticSearch (Logs), VueJS.
 - NodeJS, MongoDB.
 - Python (Scrapy), ElasticSearch
 - Trello 
 - BitBucket
 - Slack

Projetos Pessoais

 - PHP (Laravel), MySQL, Apache, Scrutinizer, VueJS (https://github.com/ciawn).
 - Python (Flask), MongoDB, Ionic (https://sufocoauto.com.br/)
 - Slack
 - Trello
 - Github

E mais umas coisas que não lembro agora.

**Comment by IgorAntun** [comment]
No trabalho:
 - NodeJS, MongoDB
 - Python, Scrapy
 - ElasticSearch
 - Neo4J
 - React
 - Slack
 - Github (com ZenHub)
 - DigitalOcean

Projetos pessoais:
 - NodeJS, MongoDB
 - React
 - Github
 - Trello

Ambos:
 - VSCode / Atom
 - Arch (Antergos) + fish shell / Windows 10 (pra algumas coisas)

**Comment by felipejsm** [comment]
Trabalho:
- Java 8
- Angularjs 1.6
- Nodejs
- Github
- Maven
- Eclipse Oxygen
- CronApp
-  SQL Server/MySQL
- Tomcat
- Windows 10

Projetos Pessoais:
- Angularjs 1.6/4
- Nodejs
- Spring Boot
- Java 8/9
- Firebase
- Ionic
- Mint 'Sonya'
- VS Code :heart: 
- Gitlab
- Github

**Comment by thiamsantos** [comment]
- PHP
  - [Slim](https://www.slimframework.com/)
  - [Twig](https://twig.symfony.com/doc/2.x/)
  - [Eloquent](https://laravel.com/docs/5.4/eloquent)
  - [Phinx](https://phinx.org/)
  - [MySQL](https://www.mysql.com/)
- Node.js
  - [Express](http://expressjs.com/)
  - [Knex](http://knexjs.org/)
  - [MySQL](https://www.mysql.com/)
- Front
  - [Vanilla JS](http://vanilla-js.com/) (dependendo do tamanho do projeto talvez [React](https://reactjs.org/))
  - [webpack](https://webpack.js.org/)
  - [Babel](https://babeljs.io/)
  - [PostCSS](http://postcss.org/)
  - [CSS Modules](https://github.com/css-modules/css-modules)
  - [cssnext](http://cssnext.io/)
  - [Browsersync](https://www.browsersync.io/)

No trabalho:
- [Vagrant](https://www.vagrantup.com/)
- [Bitbucket](https://bitbucket.org/)
- Redmine
- Mac OS
- [VS Code](https://code.visualstudio.com/)
- [iTerm2](https://www.iterm2.com/)
- Zsh

Em casa:
- [Docker](https://www.docker.com/)
- [Bitbucket](https://bitbucket.org/) ou Github
- Windows 7 :disappointed:
- [VS Code](https://code.visualstudio.com/)
- [cmder](http://cmder.net/)

**Comment by gucastiliao** [comment]
- [PHP (Laravel)](https://github.com/laravel/laravel)
- [NodeJS](https://github.com/nodejs/node)
- [Meteor](https://github.com/meteor/meteor)
--------
- [React](https://github.com/facebook/react)
--------
- [MongoDB](https://github.com/mongodb/mongo)
- [MySQL](https://www.mysql.com/)
--------
- [Docker](https://github.com/docker-library/docker)
--------
- [VSCode](https://github.com/Microsoft/vscode)
- [iTerm2](https://www.iterm2.com/) / [Zsh](https://github.com/robbyrussell/oh-my-zsh)

**Comment by mdamaceno** [comment]
Trabalho

- PHP
- Firebird
- Nginx
- Docker
- Github

Pessoal

- PHP
- Node.js
- Ruby
- PostgreSQL
- Vue.js
- Docker
- Bitbucket
- Github

**Comment by jonathas** [comment]
No trabalho:

- Node.js
- TypeScript
- AngularJS
- MongoDB
- Nginx
- Redis
- RabbitMQ
- Docker
- Jenkins
- Debian Linux
- Manjaro Linux (baseado no Arch Linux)
- Assembla
- Confluence, Jira
- Trello
- AWS S3 e CloudFront
- OVH
- VSCode

Em casa:

- Node.js
- TypeScript
- React
- MongoDB
- Nginx
- Redis
- Docker
- TravisCI
- Coveralls
- Arch Linux
- Github
- Trello
- Heroku
- VSCode

**Comment by julioc98** [comment]
No trabalho:

- Go (Golang)
- MariaDB
- Redis
- RabbitMQ
- Swagger
- VIM
- VSCode
Fora do trabalho:

- Node.JS
1. Koa
2. Hapi
- MongoDB
- Firebase
- Android
1. Java
2. Android Studio
- Golang
- VSCode

**Comment by nataliawinter** [comment]
- PHP, MySQL, MongoDB, Docker, Jenkins, Nunjucks, npm
- Trello
- Github
- Slack
- VSCode

**Comment by laurenmariaferreira** [comment]
No trabalho:
- Back: Golang
- Banco: MariaDB
- Front: Angular.JS
- Comunicação entre a equipe: Slack e Outlook
- Gestão: TFS
- Coding: VS Code

No projeto pessoal:
- Back: Go
- Banco: MySQL
- Front: Vue 2
- Gestão: Trello
- Coding: VS Code

**Comment by Cleysonlb** [comment]
No trabalho:

- backend: Ruby on rails
- manupulação de dom: Javascript
- Banco: Postgresql
- Servidor: Heroku

Em casa:

- NodeJS
- Graphql
- Ruby on rails
- Vue
- Postgresql

**Comment by carloshenriqueribeiro** [comment]
No trabalho:

   - Back: Restful API .NET (C#) - aplicação de DDD;
   - Banco: MS-SQL;
   - Front: Angular.JS;
   - Comunicação entre a equipe: Skype;
   - Gestão: VSTS (Git);
   - IDE: VS Code e Visual Studio 2017;
   - Documentação: Swagger;
   - Testes de API: Postman (Collections + Environments);
   - Gerenciamento da Equipe: Dynamics (ERP da Microsoft);

Próximas implementações:
- Scripts geradores de códigos tanto pra back quanto front;
- Automatizar testes de front;
- Implementar Runner do Postman;
- Implementar Scripts via Swagger;
- Implementar React em alguns projetos;

Em 🏠 : As vezes dou uma passada lá pra tomar banho. 😂




Carlos Ribeiro

**Comment by ericOnda** [comment]
No trabalho:

- Back-end: Node, Express, Django/Django REST, Yii
- Banco de dados: MariaDB, Postgresql, Mongo
- Front-end: Angular (1 e 2)
- Comunicação com os times : Slack
- IDE: VSCode

Casa (tecnologias que estou organizando o tempo para estudar):

- Back-end: Ruby on Rais, Laravel, GraphQL
- Front-end: Vue, React
