### ISSUE TITLE
Sobre Python...

### ISSUE THREAD

**Issue by Vitor-Felipe** [backend-br/forum#25]
Galera, ultimamente eu venho estudado Python através do [Curso em video](https://www.cursoemvideo.com/course/curso-python-3/), gostei bastante da linguagem, mas ainda tenho minhas duvidas em relação ao uso e sucesso dela na comunidade.
Já fiz umas pesquisas e descobri que da pra usar Python em praticamente tudo e que ela é realmente uma linguagem muito fácil de se aprender, mas ae que vem as dúvidas...

- Por que, Python ficou tão famoso ultimamente?
- Tem algum tipo de aplicação onde Python é considerado a melhor linguagem a ser usada?
- Você conhecem algum lugar onde eu posso aprender Python avançado?
- Já trabalharam com essa linguagem? 
- Tem mercado para programador Python?

Desde já agradeço!

**Comment by WeltonSanches** [comment]
Conheço pouco desse mercado e por isso só sei responder com precisão uma das perguntas. Mas vai ai minha contribuição.

Tem algum tipo de aplicação onde Python é considerado a melhor linguagem a ser usada?
Big Data e o ecossistema de análise de dados em geral (junto com R e algumas outras com o mesmo foco).

**Comment by reginaldojunior** [comment]
Algumas considerações:

  - Por que, Python ficou tão famoso ultimamente?
    - Acho que ele pegou fama por causa do google, como tanto outras linguagens. Mas além disso ela é ótima. 

  - Tem algum tipo de aplicação onde Python é considerado a melhor linguagem a ser usada?
    - Ela é ótima para caso de calculo númerico computacional, onde vc precisa utilizar ponto flutuantes mais exatos, por isso ela vem sendo bastante usado no mundo docente, para pesquisas, astrofisíca, inteligência artificial, Big data etc...

  - Você conhecem algum lugar onde eu posso aprender Python avançado?
    - Tem ótimos livros de Python, o que li para aprender desenvolvimento web foi o "Python para desenvolvedores 2ª edição".

  - Já trabalharam com essa linguagem?
    - Sim, trabalhei 8 meses em uma empresa só nesta linguagem. E também fiz alguns projetos meu usando ela no backend.

  - Tem mercado para programador Python?
    - Sim, acredito que não seja tanto como PHP ou Java por exemplo, mas ela vem crescendo cada vez mais e no que se diz Big Data ela é a preferida para esse trabalho, então se você tiver interrese em ser cientista de dados é uma ótima escolha para seguir os estudos. A @luizalabs usa o python no backend deles.

**Comment by Vitor-Felipe** [comment]
Obrigado pela colaboração @WeltonSanches  e @reginaldojunior, vou dar uma olhada no livro ;D
Se tiverem mais alguma dica, principalmente na parte de estudos, ficarei muito grato!!

**Comment by mstuttgart** [comment]
* Por que, Python ficou tão famoso ultimamente?

É uma linguagem muito poderosa e extremente fácil de aprender e agradavel de se trabalhar. Isso fez com que muitas empresas grandes a utilizassem, tornando-a popular. Outra coisa que ajudou, foi que ela passou a ser utilizada para ensino em algumas faculdade de renome (principalmente, nos EUA).

* Tem algum tipo de aplicação onde Python é considerado a melhor linguagem a ser usada?

Como o pessoal comentou, ela e ótima para área de análise de dados (uma das áreas em ela tem sido mais adotada) e na construção do backend de aplicações web (principalmente com Django).

* Você conhecem algum lugar onde eu posso aprender Python avançado?

Na Udemy você encontra ótimos cursos de Python. Também existem ótimo livros, como "Python para desenvolvedores 2ª edição", "Python Eficaz", "Pense em Python" e "TDD com Python".

* Já trabalharam com essa linguagem?

Sim, trabalho com Python desde 2014 utilizando ela como backend para o Odoo (um ERP opensource feito em Python) e também utilizo para outros projetos tanto no trabalho quanto em projetos pessoais.

* Tem mercado para programador Python?

Sim. A grande maioria das vagas que encontro são para desenvolver aplicações web com Django ou para utilizar Python para análise de dados.
