### ISSUE TITLE
Microservices API GATEWAY

### ISSUE THREAD

**Issue by WillianSugiyama** [backend-br/forum#26]
E aí, galera, tudo em ordem? 
Estou com um desafio meio complicado por aqui, Estamos migrando do monolítico para microservices, só que estou com um problemão,  não conheço muito gateways de api, nem como funcionam, acabei dando uma lida no da aws e me pareceu ser interessante, mas queria saber de vocês, vocês usam algum gateway? Se sim, quais. Se não, como vocês fazem essa "ponte"?

**Comment by khaueviana** [comment]
@WillianSugiyama eu não usei, mas me indicaram esse serviço do Azure: https://azure.microsoft.com/pt-br/services/service-fabric/

**Comment by mmalaquiasdev** [comment]
Fala man blz?

Eu conheço esses:
https://getkong.org/about/
https://tyk.io/
https://cloud.spring.io/spring-cloud-gateway/
https://sensedia.com/
https://www.ca.com/br/products/api-management.html

recomendo que assista:
https://www.youtube.com/watch?v=9WkRpFy3d_s
