### ISSUE TITLE
Dicas para desenvolver um CMS

### ISSUE THREAD

**Issue by pietrobelluno** [backend-br/forum#27]
Fala galera , estou com a ideia de desenvolver um cms para criação de websites , quero desenvolver algo que eu consigo fazer o back-end de sites o mais rápido possivel , seria um cms so para websites mesmo , focado no desempenho , eu tenho conhecimento em codigniter e laravel , laravel tem um cms q desenvolvemos aqui na empresa mas acho que ele tem coisas demais q  sao desnecessarias para criacao de websites , quero fazer algo mt simples , se tiverem dica de algum framework para isso alguma experiencia , sou todo ouvidos hahahah

**Comment by kivervinicius** [comment]
Lumen. Apesar que eu acredito q a "maior" e única vantagem em fazer um CMS hoje seria para o aprendizado e crescimento pessoal.

**Comment by khaueviana** [comment]
Amigão, dá uma olhada nesse artigo https://hackernoon.com/how-i-built-a-cms-and-why-you-shouldnt-daff6042413a

**Comment by khaueviana** [comment]
@pietrobp

**Comment by aicoutos** [comment]
Pretende começar do zero ou vai usar algum framework pronto como base? Acredito que a segunda opção seja a forma mais simples e rápida de se fazer um CMS hoje em dia.
