### ISSUE TITLE
Filmes e séries

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#29]
Galera, no começo do ano fiz uma [lista com alguns filmes que envolvem tecnologia de alguma forma](https://github.com/onhernandes/awesome-movies), mas não atualizo desde Janeiro e não divulguei por acreditar que ainda está incompleta. Pretendo reorganizar aquele README e deixar tabulado.

Não conheço muitos filmes ou séries que envolvem tecnologia, os que eu conheço eu coloquei na lista. Podem me dar indicações?

Também, se quiserem abrir uma issue diretamente no repositório com o nome do filme/série, seria ótimo!

[https://github.com/onhernandes/awesome-movies](https://github.com/onhernandes/awesome-movies)

**Comment by aicoutos** [comment]
olá @onhernandes, já conhece o https://hackermovie.club (https://github.com/k4m4/movies-for-hackers)?

**Comment by mstuttgart** [comment]
Eu fiz o algo parecido, só que com filmes/séries/livros/jogos que falam sobre viagem no tempo. https://github.com/mstuttgart/awesome-time-travel
