### ISSUE TITLE
1º Meetup Backend Brasil

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#31]
Estamos pensando em fazer nosso primeiro meetup no estilo roda de conversa, cada participante colocaria um assunto para discussão e todos participantes conversariam sobre no tempo máximo de 7 minutos por assunto.

O que vocês acham deste modelo?

Tem outras sugestões, ou sugestões de lugares que podemos fazer esse evento?

**Comment by woliveiras** [comment]
Será em qual estado, @reginaldojunior?

**Comment by reginaldojunior** [comment]
Este primeiro estarei organizando em SP.

**Comment by ttrivelato** [comment]
Dependendo do dia e horario posso participar =)

**Comment by reginaldojunior** [comment]
Show, estou pensando na semana após horário comercial. Acho que os melhores locais é centro, avenida paulista etc... Algum lugar próximo do metrô.

**Comment by Marlysson** [comment]
Como foi a organização do evento do meetup que aconteceu pessoal? Foi em outro local? .. Pq procurei alguma issue relacionada e não encontrei...

**Comment by onhernandes** [comment]
@Marlysson os eventos sempre são publicados aqui: 
[https://github.com/backend-br/eventos](https://github.com/backend-br/eventos)

Foi no GetNinjas. Depois tu pode entrar no meetup.com e no twitter, procura por `@BackEndBrasil` que fizemos uns tweets sobre o evento. Já temos outro marcado e acho que ainda deve ter espaço.
