### ISSUE TITLE
Documentação interna de empresas

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#32]
Qual o melhor método para centralizar a documentação interna de processos na empresa? O que vocês estão utilizando, hoje utilizo bastante o evernote mas acho ele bem ruim para isso.

**Comment by khaueviana** [comment]
Cara, uma WIKI :)

Existem diversas ferramentas que usam isso, e de todos os tipos de ferramentas que já vi, é o mais bacana.

**Comment by reginaldojunior** [comment]
A Wiki do Bitbucket é muito ruim 😠 Aqui na empresa usamos o Bit, será que tem algum projeto só de Wiki para centralizar isso?

**Comment by aicoutos** [comment]
checklist com progress bar é uma boa http://alexdeoliveira.github.io/13checklist/

**Comment by JeanLLopes** [comment]
Olá @reginaldojunior, se voce busca um gerenciamento de documentos imahinobque algum sistema de GED ( ou gerenciamento eletrônico de documentos, talvez incluso no seu ERP ) possa lhe ajudar. 
Agora se você busca algo para gerenciamento da documentação do seu código-fonte aí recomendo o uso de WIKI.

**Comment by jonathas** [comment]
Nas minhas ultimas duas empresas, Confluence da Atlassian. Funciona muito bem pra documentação e Jira pros issues, tudo integrado

**Comment by onlurking** [comment]
Na Startup que trabalho usamos o [Notion](https://www.notion.so) em peso, que é quase um editor WYSIWYG do Medium, mas é relativamente [caro](https://www.notion.so/pricing) pra implementar em uma empresa, na minha opinião.

Eu particularmente subiria uma instancia privada do [HackMD](https://hackmd.io)  ou do [MkDocs](http://www.mkdocs.org)(com o tema [Material Design](https://squidfunk.github.io/mkdocs-material/getting-started)), mas esses dois caras em questão assumem que a galera que vai manter a wiki saiba [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) e sejam usuários intermediários em computação.
