### ISSUE TITLE
Deploy para o servidor

### ISSUE THREAD

**Issue by kivervinicius** [backend-br/forum#35]
Galera, hoje como vocês fazem deploy de um projeto para produção/teste, sou da época que um ftp era o suficiente (mas improdutivo), dai surgiram diversas ferramentas para CI (Travis, Jenkins, Circle) mas até hoje nunca utilizei nada, fazemos tudo com sh, para nós que estamos acostumados não se torna um fardo é até produtivo, mas sempre com aquela aparência de "re-invenção da roda", como vocês fazem e quais dicas podem me dar para tentar ser mais produtivo e estar no mesmo caminho de outras empresas.

PS: Hoje nós temos projetos em Java, C# e Node

**Comment by khaueviana** [comment]
Olá @kivervinicius 

O que já usei e recomendo, é o VSTS (Visual Studio Team Services).

Cara, essa plataforma tem toda a gestão do projeto, desde board de atividades até tasks de CI.

É muito boa, e não só para tecnologias MS 💃 

https://www.visualstudio.com/pt-br/team-services/?rr=https%3A%2F%2Fwww.google.com.br%2F

Qualquer dúvida, cola aqui!!!

**Comment by JeanLLopes** [comment]
Olá @kivervinicius
Tambem uso o VSTS pra gerenciamento de deploy assim como o @khaueviana.

Recomendo muito.. Qualquer duvida é so dar um tok

**Comment by kivervinicius** [comment]
obrigado pessoal, estou pesquisando sobre

**Comment by jonathas** [comment]
Configurei um servidor com Jenkins aqui na empresa e um webhook no serviço de git que usamos (Assembla) pra rodar o CI e CD quando ocorre um commit. Bem prático, recomendo dar uma pesquisada sobre. Pra projetos open source tenho utilizado o TravisCI, ja que é de graça pra projetos desse tipo.

**Comment by allbarbos** [comment]
Aqui na firma utilizamos C# .NET, os deploys são manuais também, no entanto uma coisa que vem prejudicando um pouco é a questão de subir o deploy no momento em que o usuário está finalizando uma compra ou qualquer outra ação e quebra no meio.

Vocês utilizam algo pra evitar isso? O VSTS facilita isso também?

**Comment by kivervinicius** [comment]
@allbarbos de uma pesquisada sobre blue-green deployment
