### ISSUE TITLE
Daily/Challenges BackEnd

### ISSUE THREAD

**Issue by crisgon** [backend-br/forum#36]
Olá, pessoal. Já vi diversos dailys pro pessoal que é FrontEnd, como o 30 days 30 sites, mas nunca vi nada desse tipo pra quem estuda BackEnd. Existe algum?

**Comment by rafa-acioly** [comment]
Este site tem desafios pra diversas linguagens, desde GO, PHP, Kotlin até Scala

http://exercism.io/

**Comment by onhernandes** [comment]
Voto por criar um projeto de daily challenges na org do back-end br e o pessoal colocar ideias pra desafios nas issues, depois revisamos e colocamos. @reginaldojunior

**Comment by reginaldojunior** [comment]
Acho interresante fazemos esses desafios, mas temos que sempre movimentar senão vai ser um repositório a mais e parado, tem que ter alguém que vai ser responsável em divulgar analisar e fazer os desafios.

**Comment by onhernandes** [comment]
@reginaldojunior posso cuidar do projeto \o

**Comment by carloshenriqueribeiro** [comment]
1 ideia : o responsável deverá colocar no mínimo 1 desafio por período a
definir (semanal ou quinzenal), assim garantimos o mínimo de movimentação
no Repo.

Carlos Ribeiro

**Comment by Marlysson** [comment]
Opa, ótima iniciativa, um tempo atrás iniciei uma parecida com exercícios iniciantes para python .

Eu era o responsável por criar alguns e incentivar o pessoal a contribuir.

Fomos razoavelmente longe :smile: , mas como citado alguns projetos podem parar por diversos motivos.

Um Repo com desafios ( principalmente de featured reais de software ) para treinar a mente criativa para resolver problemas seria incrível.

Tem mais alguem na gente desse projeto?
Estou interessado em contribuir ativamente..

**Comment by Marlysson** [comment]
Sera por linguagem ou independente.. Contanto que resolva da melhor maneira..

E será para iniciantes.. Como os desafios de repositórios ou funcionalidades ( assim como os challenges do frontend-challenge )

**Comment by reginaldojunior** [comment]
Não começamos ainda, mas posso criar o repósitorio então para continuamos com essa ideia? 

@Marlysson fica responsável ai por movimentar os desafios?

**Comment by Marlysson** [comment]
Opa, posso sim, só saber mais detalhes de como seriam..

Quais tipos de desafios poderiam ser, em quais áreas.. Alguma forma de conferência..

Teria mais alguém para colaborar? Para discutir as coisas..

**Comment by reginaldojunior** [comment]
@onhernandes alguma ideia?

**Comment by onhernandes** [comment]
@reginaldojunior tenho um de front-end: https://github.com/onhernandes/front-challenges
Tá parado faz um bom tempo, mas vou usar como base aqui.

Acho que a organização ficaria melhor caso fosse por níveis de dificuldade e/ou temas, como implementação de design patterns e etc. Um sumário no começo separando três categorias comuns(básico, médio, avançado) e outras mais genéricas, como implementação de Design Patterns, uso de Generators, etc.

No caso do Front-End Challenge, eu preferi que colocassem os arquivos de cada desafio dentro de pastas no mesmo repositório, já que nada disso envolvia `package managers` e coisas maiores. 

No caso desse, acredito que seria mais viável separar por repositórios dependendo do tema, um CRUD com algumas coisas a mais pode abranger vários desafios ao mesmo tempo. Exemplo: uma API(tema) pode ser usada pra resolver 3 desafios:  segurança nas requisições, trabalhar com filas e async.

Sendo assim, podemos dividir o README.md em duas partes:
1) Temas/Features(um CRUD simples, um proxy, uma API, etc)
2) Desafios(usar XYZ, usar DP, usar Generators e Async, etc)

Nisso, alguém pode escolher um tema simples e algumas features, e depois pegar alguns desafios e praticá-los em um tema. Tudo isso em um repositório a parte, do próprio desenvolvedor.

**Comment by Marlysson** [comment]
@onhernandes mas não seria difícil especificar uma dificuldade genérica ? Pois difícil para alguns pode ser fácil para outros..

O lance das features pode ser interessante.. Mas e no caso que os desafios usarem mais features.. Ele se repetiria ou haveria features muito genéricas?

Estava coletando alguns challenges de backend como o de front ( específico para vagas em empresas , mesmo que já tenham passado ).

E pensando mini-cenarios a serem criados..

Ex:

- Clone do sistema de drag-in-drop do trello
- Implementar sistema de eventos em compras
- Implementar carrinhos de compras ( com todo o fluxo )

Tudo isso podendo ser especificado em passos e mais detalhes de como poderiam ser feitos.. Para não só criar e jogar lá..
.
E poderia até rolar um compartilhamento de como os users resolveram/implementaram determinado trecho/lógica.

Achei eese site.. Pode ser uma base:

https://pybit.es/pages/challenges.html

**Comment by Marlysson** [comment]
Pessoal estive pesquisando alguns desafios para ter como base, achei esse, o que acham?

https://github.com/Creditas/challenge/tree/master/backend

**Comment by onhernandes** [comment]
Tive essa mesma barreira quando fiz o front-challenges. O jeito foi separar conforme o que eu acreditava ser básico ou não, tive ajuda de alguns amigos pra conseguir ter uma base. 

Caso haja mais features, o dev pode escolher entre criar um novo projeto, ou usar um que já tenha criado. 

No back-end, não tem como criar um projeto e modularizar ao ponto de outra pessoa usar o que você fez sem adaptações. É muito mais fácil/prático eu escolher um tema(e-commerce) e dentro dele implementar várias features e completar desafios(gerenciamento de rotas, carrinho, checkout múltiplo, etc) do que refazer o mesmo setup pra um projeto várias vezes. Também posso fazer um CRUD simples de um blog, resolvendo alguns desafios, e abrir outro projeto pra fechar outros. 

A ideia de ter temas, features e desafios é justamente dar ao desenvolvedor a liberdade de escolher como, onde e quando ele quer treinar aquelas features e desafios, também quando parar(são projetos de prática, não necessariamente, pra manter).

**Comment by reginaldojunior** [comment]
@onhernandes 

https://github.com/backend-br/desafios

**Comment by mstuttgart** [comment]
Conforme o @onhernandes comentou, trabalhar por temas parece interessante!
