### ISSUE TITLE
Conteúdos e livros sobre conceitos, técnicas, boas praticas, design patterns etc..

### ISSUE THREAD

**Issue by Cleysonlb** [backend-br/forum#38]
Fala galera beleza?! Faz um tempo que to buscando conteúdos para evoluir no conceito e teoria em programação de forma agnóstica a linguagem/framework.
Alguém tem indicação de livros, blog posts, cursos etc ? Ou até mesmo experiências pessoais que te tornaram um programador melhor!

**Comment by reginaldojunior** [comment]
Cara de cabeça de livro recomendo 

Clean Code do Robert C. Martin.

**Comment by rafa-acioly** [comment]
Livro: 
O Programador Pragmático

**Comment by weltonsanches** [comment]
Clean Code - Uncle Bob
Padrões de Arquitetura de Aplicações Corporativas - Martin Fowler
Refactoring to Patterns - Joshua Kerievsky
TDD - Kent Beck
Implementing Domain-Driven Design - Vaughn Vernon

Além dos já citados esta é uma lista para próximas leituras (ainda não li nenhum rs).

**Comment by Marlysson** [comment]
Sobre design patterns e refatoração tem esses sites ( pode ser aplicado para a maioria das linguagens ):

https://sourcemaking.com/design_patterns
https://sourcemaking.com/refactoring

**Comment by Cleysonlb** [comment]
@Marlysson cara que dica animal!!!!!!!!!! Valeu 😃

**Comment by Marlysson** [comment]
@Cleysonlb sim sim :smile: esse site é um poço de aprendizado kkk

**Comment by mstuttgart** [comment]
* Como ser um desenvolvedor melhor - Pete Goodliffe
* O programador apaixonado - Chad Fowler

**Comment by OtavioHenrique** [comment]
Não é um livro muito para mercado mas sempre recomendo o CLRS:

Introduction to Algorithms - Thomas H. Cormen

Versão traduzida - Algoritmos: Teoria e Prática

**Comment by houstondapaz** [comment]
Achei muito boa as indicações https://hipsters.tech/grandes-livros-de-tecnologia-hipsters-113/
