### ISSUE TITLE
Organização de código - MercadoLivre SDK PHP

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#39]
Galera, estou trabalhando numa nova versão do [SDK do MercadoLivre em PHP](https://github.com/onhernandes/php-sdk/tree/dev/src) mas estou tendo uma certa confusão com a organização do código.

O que acontece é que, até aqui, fiz da seguinte forma:

- Meli.php (classe de conexão)
- MeliUser, MeliProduct, etc (classes herdeiras de Meli.php)

Todas as classes são herdeiras da classe `Meli.php`, apenas para fazer requisições específicas, tratar erros, etc. Estou tendo um pequeno problema na organização do código, porque não necessariamente alguém usaria a classe de produto com a classe de usuário, então, de começo coloquei apenas pra passar as chaves(`client_id`, `client_secret`, `access_token`, `refresh_token`) no construtor da classe.

Mas, isso fica repetitivo e tá me dando uma certa agonia. Minha idéia é separar totalmente as classes, e ao invés de passar as chaves nos construtores de cada uma, apenas recebia a classe de conexão como parâmetro.

Minha pergunta é: qual seria melhor pra vocês, no geral? Ter uma classe de conexão e injetar ela no construtor de outras, ou deixar que cada qual receba as credenciais?

Minha preocupação agora é sobre qual seria mais útil pros outros devs. Por mim, ficaria a opção com injeção de dependência, mas quero ouvir de vocês.

Eu sei que o código ainda tá bem bagunçado, mas estou melhorando. Estou passando tudo pro `Guzzle` e ainda vou adicionar suporte pro Laravel.

Outra coisa, se me permitirem rs, em todas as classe, uso `Meli` como prefixo, com o namespace final ficando `MeliProduct`, `MeliUser`, etc. Fico na dúvida se continuo usando `Meli` como prefixo, ou deixo apenas no namespace raiz e o restante normal, como `Product`, `User`, etc.

**Comment by rafa-acioly** [comment]
namespace: acho que poderia remover a redundância dos nomes deixando apenas por exemplo `Meli\Product`, Meli\User` e etc.


Abstração: você pode deixar os verbos `http` em suas respectivas classes que estendem uma outra classe abstrata; por exemplo:

```
abstract class ApiAbstract
{
    public function post($var);
    public function get($var);
    public function put($var);
    public function delete($var);
}
```

```
class Product extends ApiAbstract
{
    ...
}
```
desse jeito que você implementa os métodos que forem necessários em cada classe.

Disponibilidade de recursos:

Na classe principal `Meli` seria interessante se retornasse uma instancia do que foi requisitado por exemplo;

```php
class Meli
{
    public function products()
    {
        return new \Meli\Product($data);
    }

    public function users()
    {
        return new \Meli\User($data);
    }
```
Fazendo desta maneira você conseguira adicionar outros recursos direto na classe principal e mesmo assim manter a divisão de responsabilidade nas classes, veja abaixo como ficaria a instancia principal:

```php
$meli = new Meli($site $credentials);
$meli->products()->get($data);
$meli->products()->post($data);
$meli->users()->put($data);
$meli->users()->delete($data);
```
