### ISSUE TITLE
Processamento de uma grande quantidade de dados.

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#4]
Imagine o seguinte cenário, um banco de dados com umas 500 mil registros, onde precisamos ler estes registros e processar eles para uma API externa, qual a forma mais inteligente de processar isso. Pegar de 100 e 100, processar por um foreach/for ou algo do tipo, o que vocês costumam fazer nestes casos?

**Comment by Arkanius** [comment]
Não sei o seu cenário, mas quando tive problemas com isso resolvi utilizando cache (redis) e filas (no Laravel). Que processamento você precisa fazer antes de enviar os dados para uma API externa?

**Comment by reginaldojunior** [comment]
Então, eu estou fazendo meio que por passos agora.

Eu tenho duas API que tenho que consultar neste processo, a solução que encontrei no momento, foi a seguinte.

Na API A que puxo os dados, estes dados são produtos, tenho 32 mil registros para consultar, ao invés de puxar e já enviar para API B. Eu puxo, gravo em um tabela no banco de dados chamada products_queue com status = 0. Então, outro serviço pegar estes registros com status = 0 de 100 e 100 e envia para a API B e se tiver sucesso, realiza o update em products_queue com status = 1

**Comment by dzfweb** [comment]
Iria sugerir utilizar algum MessageBroker como RabbitMQ para enfileirar o processamento de forma inteligente, escalável e rastreavel e  criar os executores para realizar o processamento com MassTransit. Você pode gerenciar as re-execuções, logar as falhas, e escalar da melhor maneira possível.

Um bom material de estudo para ter uma noção do desta arquitetura pode ser visto neste vídeo:
https://www.youtube.com/watch?v=3j0HEHkksCU&t=28s 

Eu tenho um exemplo de uso desta arquitetura neste repositório: 
https://github.com/dzfweb/rabbitmq-sample

**Comment by nicholasess** [comment]
Pode usar o SQS da Amazon pra isso também.

https://aws.amazon.com/pt/sqs
