### ISSUE TITLE
[OFF] - Aplicativo indicação de músicas

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#40]
Ae pessoal, fiz um aplicativo que faz indicação de músicas para os seus amigos. Seu amigo precisa ter uma conta no aplicativo então você consegue indicar musicas para ele.

A URL do app é essa: http://tracks.backendbrasil.com.br/signup/

É opensource, vou transferir o repositório para o backend brasil depois, já que estou utilizando o subdominio nosso rs.

https://github.com/reginaldojunior/indicate-songs

Aceito indicações de músicas usuário (Reginaldo Junior) rs, feedbacks de bugs, sugestões de melhorias e etc...

**Comment by Pedro-Souza** [comment]
Aconteceu algo com o link?

**Comment by reginaldojunior** [comment]
Caiu! Vou voltar com ele, ainda não está com nginx, estou usando o proprio server do django. To fazendo mais algumas implementações para mudar isso.

**Comment by reginaldojunior** [comment]
![image](https://user-images.githubusercontent.com/7466894/35678219-b34804ee-0739-11e8-8ec6-5180fba2cc4b.png)

Está on novamente!

**Comment by Marlysson** [comment]
Off novamente?

**Comment by reginaldojunior** [comment]
Sim, fiquei de férias um tempo e não mexi mais nisso, vou arrumar e volto aqui avisando vocês.
