### ISSUE TITLE
Organização do cron

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#41]
Como vocês organizam tarefas do crontab nos seus projetos?

**Comment by jonathas** [comment]
Eu tenho feito com um container minusculo em Alpine Linux
https://jonathas.com/scheduling-tasks-with-cron-on-docker/

**Comment by onhernandes** [comment]
@jonathas boa! Vou dar uma olhada.

**Comment by wbotelhos** [comment]
Em qual tipo de projeto @onhernandes ?

Se estiver usando Rails, a gem [whenever](https://github.com/javan/whenever) escreve pra você. O comando pode ser feito durante o deploy.

**Comment by onhernandes** [comment]
São vários projetos em Laravel, queria poder organizar melhor os processos do crontab de maneira que não corra o risco de vários processos pesados executem ao mesmo tempo. Pensei em montar uma planilha com horários e os devidos comandos pra separar, etc

**Comment by wbotelhos** [comment]
É interessante você ter os horários separados sim. No caso do Whenever, como temos um arquivo chamado `schedule.rb` para manter todas as crons, lá mesmo definimos os horários em formato como `1:00`, `5:00` etc. Organizando cada um na ordem alfabética, fica fácil gerenciar.

Tenta achar um tradutor de string tipo `3:30` para o formato cron `* * * * *`, deve ter algum por ai, assim você tem uma organização visual.

**Comment by onhernandes** [comment]
Hmmmm...boa, vou dar uma olhada sobre. Valeu!
