### ISSUE TITLE
Newsletter sobre carreira em desenvolvimento de software

### ISSUE THREAD

**Issue by woliveiras** [backend-br/forum#42]
Galera, estou criando uma newsletter sobre carreira em desenvolvimento de software onde vou compartilhar dicas, novidades e sugestões sobre carreira na área, seja sobre programação, design, gestão, etc.

Para se inscrever é só entrar [neste link](http://bit.ly/newsletter-dev-career)

Se tiverem dicas, sobre como melhor atender as pessoas que estiverem se inscrevendo na lista, podem me enviar aqui também. :heart:

**Comment by onhernandes** [comment]
Boa! Qual frequência dos emails? Por semana?

**Comment by woliveiras** [comment]
Vai ser semanal mesmo, mano

Por enquanto estou levantando ideias da galera e depois vou começar a mandar brasa 

Vou criar uma landing pra colocar as edições também :D

**Comment by Pedro-Souza** [comment]
@woliveiras Vai começar quando?

**Comment by woliveiras** [comment]
Fala, @Pedro-Souza 

Eu estou em processo de troca de emprego, por isso demorei

Me desculpem, viu

Começo daqui a um mês, se tudo der certo :pray: 

O processo de adaptação ao trampo novo está tenso! iHAIHAHIA

**Comment by kirmayr** [comment]
Aeeew parabéns @woliveiras

**Comment by khaueviana** [comment]
Toopp
