### ISSUE TITLE
Recursos para aprender sobre o Spring MVC Framework?

### ISSUE THREAD

**Issue by KumoMg** [backend-br/forum#43]
Boa noite!

Eu queria saber se alguém poderia me recomendar algum tutorial, guia, site para poder aprender o Spring MVC Framework?

**Comment by kivervinicius** [comment]
@KumoMg  bom e barato é o Udemy, bom e barato

https://www.udemy.com/spring-mvc-tutorial-for-beginners-step-by-step/

**Comment by felipejsm** [comment]
@KumoMg, beleza?
As referências que mais uso, normalmente, são as da pivotal e do Baeldung
Eu as acho bem completas e claras
E são 0800 \o/
## Nacionais
[algaworks](http://blog.algaworks.com/spring-mvc/)
[caelum](https://www.caelum.com.br/apostila-java-web/spring-mvc/#adicionando-tarefas-e-passando-parmetros)

## Internacionais
[baeldung](http://www.baeldung.com/spring-mvc-tutorial)
[Referência Oficial](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html)
[Referência Oficial II](https://spring.io/guides/gs/serving-web-content/)

**Comment by jonathas** [comment]
Recomendo os cursos da Alura e o Baeldung

**Comment by mmalaquiasdev** [comment]
@KumoMg o quanto você sabe de java e spring?
