### ISSUE TITLE
Boas tecnologias para se trabalhar atualmente e manter um workflow tecnológico atualizado

### ISSUE THREAD

**Issue by Marlysson** [backend-br/forum#48]
Pessoal ultimamente tenho pesquisado algumas tecnologias e metologias que possam melhorar tanto o conhecimento sobre computação quando sobre maneiras de se construir softwares resilientes e de boa qualidade. Pensando nisso, gostaria de saber o que vocês têm usado atualmente que consideram boas práticas ou que contribuem para um bom software, com relação à tecnologias recentes..

Por exemplo: 

- Uso de docker
- Uso de message brokers 
    - Celery
    - Rabbit-MQ
    - ActiveMQ 
    - Redis
- Automatizadores/Empacotamento/Ambientes
    - Maven ( Java )
    - NPM Scripts ( Javascript )
    - Pipenv ( Python )
- Testes
    - Selenium
    - Arquilian ( Java )

Enfim, nessa área de tecs atuais..

Desde já obrigado.

**Comment by onhernandes** [comment]
Gosto de usar o `gulp` sempre que possível pra gerenciar tarefas de build e etc. Mas a maioria dos projetos que pego com front-end e etc, já tem o webpack configurado ou coisa parecida.

Testes em JS tu pode usar o NightWatchJS pra testes E2E, o Jasmine/Jest/Chai, etc pra testes unitários.

Pra testes de interação, além do Selenium, tem também o PhantomJS(o desenvolvimento dele foi parado, porém continua estável)

Em relação ao docker, tem o docker-compose + laradock com um ambiente pré-configurado pra ti e o Ansible pra automatizar as coisas.

PHP tem o composer pra gerenciar pacotes e o PHPUnit pra testes unitários.

Além de tudo isso, vc pode usar o supervisor pra quando quiser manter X processos abertos(garantir que eles reiniciem sempre que um morrer), salvar logs de erros e manter X cópias deles rodando ao mesmo tempo - isso é ótimo em projetos que tu precisa de workers pra trabalhar com filas, como no Laravel.

Bitbucket (e acredito que o gitlab/github tbm tenham) tem pipelines, pra rodar testes e etc antes do merge ou coisas assim.

De cabeça, lembro só disso agora.
