### ISSUE TITLE
Por onde um front deveria começar os estudos em backend?

### ISSUE THREAD

**Issue by clarabatt** [backend-br/forum#51]
Então galera eu sou frontend a bastante tempo e queria aprofundar mais meus estudos em back, o que sei é bem superficial.
Fiquei um pouco perdida por onde deveria começar, quais assuntos estudar primeiro. Não sei se back tem uma linha bem definida de estudos como no front, HTML -> CSS -> JS -> ..., dei umas pesquisadas mas achei tudo muito vago, então gostaria da opinião de vocês sobre qual estratégia/linha de estudos seguir 😁 

Valeu pela atenção de vocês (:

**Comment by gucastiliao** [comment]
Opa! Tudo bem?

Eu gostava bastante de front-end, mas comecei a mexer com o desenvolvimento de APIs e isso me deu muita vontade de aprofundar os estudos em back-end, foi quando comecei a pesquisar mais sobre o funcionamento de APIs, servidores, banco de dados e etc.

Veja sobre esses assuntos:
- API
- Métodos HTTP
- Banco de Dados

Eu aconselho você a seguir por esta linha, pesquisando como funcionam essas partes que ligam o back-end, praticando e participando de comunidades para tirar dúvidas ou ajudar outras pessoas.

Isso é bem o básico mesmo, mas pegando essa parte você já consegue se aprofundar em outros assuntos que envolvem o desenvolvimento back-end.

Dê uma olhada também nessas issues criadas aqui no forum, acredito que seja de grande ajuda:
[Como começar na área BackEnd](https://github.com/backend-br/forum/issues/2)
[Conteúdos e livros sobre conceitos, técnicas, boas praticas, design patterns etc..](https://github.com/backend-br/forum/issues/38)

**Comment by allbarbos** [comment]
@clarabatt Se quiser entrar de cabeça, aconselho primeiro a estudar/conhecer a parte de Algoritmos e Estrutura de dados, pois é algo que você irá usar em qualquer linguagem que escolher e qualquer software que venha desenvolver. A partir daí acho que o próximo passo seria escolher uma linguagem, banco de dados e etc...

Um livro bacana de algoritmos é [esse](https://www.amazon.com.br/Entendendo-Algoritmos-Aditya-Y-Bhargava/dp/8575225634), leitura leve e bem explicado.

**Comment by khaueviana** [comment]
Complementando o que o pessoal já falou, eu recomendo daru ma olhadinha em Node :D Javascript em todos os lugares \o

**Comment by thiamsantos** [comment]
@clarabatt dá uma olhada no [developer roadmap](https://github.com/kamranahmedse/developer-roadmap#-back-end-roadmap).
