### ISSUE TITLE
Rails - Autenticação Rails Devise

### ISSUE THREAD

**Issue by Cleysonlb** [backend-br/forum#54]
Fala galera beleza?! To tentando configurar e autenticar o devise na minha aplicação RAILS no modo API, mas não queria usar o devise token auth pra isso, quero usar somente o email e senha normal, alguem sabe algum conteúdo legal falando/ensinando?

**Comment by OtavioHenrique** [comment]
Já procurei por isso também e não encontrei nada muito concreto, sempre tem falando para usar o `devise_token_auth` ou no máximo o `knock`. Se achar compartilha pf

**Comment by Cleysonlb** [comment]
@OtavioHenrique trocando uma ideia com uns amigos, descobri que o devise por si só não tem suporte na utilização do rails no modo api...
