### ISSUE TITLE
Back Ends iniciantes buscando trampo

### ISSUE THREAD

**Issue by woliveiras** [backend-br/forum#55]
Galera, o @training-center possui um projeto para ajudar pessoas iniciantes a entrarem na área de desenvolvimento de software e temos algumas pessoas buscando trampo como Back End, quem puder ajudar, compartilhem ae nas empresas de vocês ou nas redes sociais: [Back Ends buscando o primeiro trampo](https://github.com/training-center/primeiro-trampo/issues?q=is%3Aissue+is%3Aopen+label%3A%22Back+End%22)

**Comment by reginaldojunior** [comment]
Boa, temos algumas vagas mas não tem nada especifico para primeiro trampo, vou começar divulgar esse repo.

**Comment by khaueviana** [comment]
aproveitando a deixa, @woliveiras ajuda na divulgação dos nossos meetups!!! :smile:

**Comment by woliveiras** [comment]
Opa! Sempre @khaueviana.

Mesmo quando não compareço, divulgo.

Vocês são feras! \o/

**Comment by fsrocha-dev** [comment]
@woliveiras muito bom o serviço que você tem prestado em ajuda a galera que está iniciando no mundo dev.

**Comment by woliveiras** [comment]
É, nozes, @fsrocha-dev! :metal: :metal: :metal:

**Comment by tberne** [comment]
Para a galera do RJ e SP, tem umas vagas abertas na [Lumis](http://www.lumis.com.br). Veja elas [nesse site](https://vagas.com.br/lumis).
