### ISSUE TITLE
Novas Tags no forum de vagas

### ISSUE THREAD

**Issue by rafa-acioly** [backend-br/forum#56]
Vide #55 

O que acham de adicionar tags de nivel para as vagas?
- Junior
- Pleno
- Sênior

Atualmente existem apenas  tags com os nomes da linguagens requeridas por cada vaga.

**Comment by OtavioHenrique** [comment]
Por que não adicionar `estágio` também?

**Comment by thiamsantos** [comment]
Mas já não existe essas tags? 

- [Estagiário](https://github.com/backend-br/vagas/labels/Estagi%C3%A1rio)
- [Junior](https://github.com/backend-br/vagas/labels/Junior)
- [Pleno](https://github.com/backend-br/vagas/labels/Pleno)
- [Senior](https://github.com/backend-br/vagas/labels/Senior)

**Comment by rafa-acioly** [comment]
de fato @thiamsantos procurei e por algum motivo não aparece da primeira vez :disappointed:
