### ISSUE TITLE
Gerenciamento de senhas no trabalho

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#57]
Como vocês gerenciam as senhas no trabalho?

Várias plataformas já permitem o uso de subcontas + permissões, mas e quando a plataforma não suporta, como vocês gerenciam as senhas? Entregam todas para os devs, ou criam um acesso pra cada, cada um com sua senha personalizada e tals?

Digamos que eu esteja usando uma aplicação para fazer XYZ mas só tenha um único login, sem organização de subcontas e etc, mas preciso que um dev tenha acesso para configurar, ou que tenha acesso para testar, N opções. Como controlam os acessos?

Tem alguma coisa pra se precaver caso alguém enlouqueça e queira ferrar com tudo?

**Comment by reginaldojunior** [comment]
https://1password.com/

você pode usar as planilhas do google também, zoeira uhadhfuauhsdf

**Comment by wbotelhos** [comment]
Usamos o https://www.onelogin.com aqui no GetNinjas e funciona muito bem.

**Comment by onhernandes** [comment]
@wbotelhos valeu, vou dar uma olhada nele

**Comment by gerardo-junior** [comment]
Eu gosto de usar keepass com https://keepassxc.org/ e um addon no browser no desktop, https://play.google.com/store/apps/details?id=com.kunzisoft.keepass.free no celular e faço sync dos .kdbx's, com algum um serviço de sync. de graça e bem seguro
