### ISSUE TITLE
Popular dados falsos no Mongoose

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#58]
Como vocês populam dados falsos no Mongoose para casos como, um dev novo chega na empresa e precisa de uma cópia do banco com alguns dados para testes(usuário, etc)?

**Comment by OtavioHenrique** [comment]
Nunca trabalhei diretamente com Mongoose, mas acredito que você poderia criar um arquivo de seed, mas dependendo do tamanho do projeto se torna inviável.

**Comment by jonathas** [comment]
Da uma testada nisso: https://github.com/andrejewski/fakegoose

**Comment by onhernandes** [comment]
@OtavioHenrique então, pensei em fazer isso, mas pelo menos na empresa são 24 collections.

@jonathas curti esse, ele usa o próprio schema, daí só preciso adicionar o fake aparentemente. Vou brincar com ele mais tarde, valeu!

**Comment by wbotelhos** [comment]
@onhernandes Te recomendo fazer manual, mesmo que demore no início, já que não fizeram enquanto criavam os models. Isso porque o seed, ao longo do tempo, pode ficar complexo com muitos relacionamentos, logo mantê-los será custoso.

Se acostume a criar um model, criar os testes e já criar o seed, ao menos o suficiente para preencher uma paginação + 1, assim você não terá que manter outro "serviço", neste caso o populador de seed.
