### ISSUE TITLE
Como configurar Laravel Homestead sem virtualização?

### ISSUE THREAD

**Issue by kvnol** [backend-br/forum#59]
Bom dia, galera.

Há algum tempo venho apanhando com alguns projetos que utilizam Laravel (sou front-end) pois não consigo configurar o Homestead no meu pc, pois a BIOS não suporta virtualização. Há alguma outra forma de configurar?

**Comment by onhernandes** [comment]
Acho que é mais fácil você subir um PHP + MySQL local, só configurar no `.env` da aplicação e rodar o `composer install`.

Tu usa Windows ou Linux?

**Comment by kvnol** [comment]
Pode crer, @onhernandes. Atualmente eu faço isso, mas alguns projetos tem peculiaridades conforme a hospedagem, como versão de PHP diferente e tal. O Homestead é perfeito pra isso.

**Comment by onhernandes** [comment]
Você pode trocar o homestead pelo Docker. Tem o [laradock](https://github.com/laradock/laradock) que já vem com bastante coisa pronta também e você pode controlar as versões do PHP. Serve pra muita coisa, inclusive aqui na empresa temos NodeJS e MongoDB na 3.2, mas tive problemas pra instalar essa versão na minha máquina, então tive que usar o Laradock pra instalar o MongoDB na 3.2

Pode ler esse artigo [aqui, ele te dá uma introdução ao Docker + Laradock + Laravel](https://medium.com/@hermesmartins/rodando-o-laravel-em-um-abiente-docker-com-o-laradock-befe2bd0f672)

**Comment by kvnol** [comment]
Massa, @onhernandes. Vou testar aqui! Valeu.
