### ISSUE TITLE
Um repositório para organizar eventos e palestras das meninas 

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#6]
O que vocês acham de um repositório para as meninas organizarem os eventos delas, e eles terem maior gestão dos projetos?

**Comment by susanasilva** [comment]
Acredito que seja uma ideia muito válida.

**Comment by reginaldojunior** [comment]
Show! Vamos organizando as coisas gerais primeiro, e dps já vamos pensando nisso. :smile:

**Comment by ThiagoLuizNunes** [comment]
Ótima idéia, tem meu apoio.

**Comment by khaueviana** [comment]
Pode ser um post fixo, mas com destaque para conteúdo e comunidades que estão incluindo as mulheres. 

No BrazilJS rolou muita coisa legal sobre a mulherada na área :)
