### ISSUE TITLE
Skills de front-end necessárias para um dev back-end. 

### ISSUE THREAD

**Issue by vitoraalmeida** [backend-br/forum#60]
Estou iniciando no mundo do desenvolvimento web e não tenho muito gosto pela parte visual do negócio. Entendo a importância, inclusive aprecio um bom front, mas não sirvo para fazê-lo, o que me leva à pergunta : qual o mínimo que devo saber de front-end? 
Sei que o básico é a trindade HTML/CSS/JavaScript, mas o que eu devo ser capaz de fazer no front pra seguir adiante de consciência limpa?

**Comment by Cleysonlb** [comment]
Se seu foco é backend não "perca" muito tempo no front, hoje o universo frontend engloba diversas coisas que se você for a fundo não vai conseguir conciliar tudo...
Saiba um básico de HTML, CSS e JS, saiba mexer no `inspec` do navegador e entenda como o browser renderiza a página, acho que é um caminho mais que necessário pra você seguir de consciência limpa! HAHA

**Comment by vitoraalmeida** [comment]
@Cleysonlb , @wbotelhos , eu fico lendo sobre o quanto Full Stack's são desejados pelo mercado e fico na neura de estudar tudo por igual. E como não tenho gosto para o front, fico empacado, até pq não tenho estímulo para estudar ou praticar. Mas obrigado pelas dicas.

**Comment by khaueviana** [comment]
Full Stack, nunca nem vi

**Comment by mdamaceno** [comment]
Eu recomendo fortemente esse repositório https://github.com/kamranahmedse/developer-roadmap

Acho que ele sintetiza bem o caminho que se deve seguir.

**Comment by mstuttgart** [comment]
@vitoraalmeida também penso muito nisso. Entretanto, algum tempo atrás ouvi (não me lembro se foi em algum podcast, blog ou videoaula) que um Fullstack precisa ser *especialista* em algo (backend, por exemplo) e *competente* nas outras áreas (frontend, infra e etc). Não é preciso estudar muito pra perceber que é dificil, pra não dizer impossivel, ser especialista em tudo. Eu mesmo já decidi me focar em backend e aprender sobre as outras áreas (ser competente) com o tempo. Sou ansioso por natureza, e tentar estudar de tudo estava mais atrapalhando do que ajudando kkk (por mais que eu tentasse me organizar).

No mais, o repositório que o @mdamaceno recomendou é um excelente ponto de partida. Estou usando ele  como guia de estudos :)

**Comment by fsrocha-dev** [comment]
@vitoraalmeida Cara creio eu que o caminho para um Desenvolvedor se tornar um FullStack, não é simplesmente ele escolher skills e sair codando, mas é um caminho natural, conhecimentos que você vai adquirindo conforme o seu amadurecimento como desenvolvedor.Então o meu conselho é escolha sua linguagem e aprenda os conceitos primeiro depois você vai adicionando as skills frontend aos poucos.
Html5, Css3, JavaScript, Saas, Less, Bootstrap, Jquery -> o leque é enorme.
