### ISSUE TITLE
Não expor dados em API - Laravel 5.6

### ISSUE THREAD

**Issue by mayronceccon** [backend-br/forum#61]
Estou desenvolvendo uma API com o Laravel 5.6, onde em meu banco tem por exemplo o campo cordescricao, ao fazer o enviar de um POST não queria que o usuário enviasse "cordescricao" no raw, mas sim "descricao" e o sistema identifica-se esta referencia (de para) e ao salvar pelo Eloquent não retornasse o erro de campo não encontrado.

Minha dúvida não é de como fazer esta lógica, mas sim se no Laravel existe algo nativo (elegante) que faça isto?

Para o retorno dos dados estou utilizando JsonResource, onde os campos são retornados da forma que eu quero, seria algo inverso disso.

**Comment by felipemfp** [comment]
Acho que [Accessors e Mutators](https://laravel.com/docs/5.6/eloquent-mutators#accessors-and-mutators) é o que você quer.
