### ISSUE TITLE
Pattern para verificar serviço

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#62]
Alguém conhece algum pattern que resolva o seguinte cenário: Verifica se determinado serviço está disponivel se sim, uma ação a ser tomada, caso contrario, execute outra ação, ou apenas não execute o serviço em questão?

**Comment by wbotelhos** [comment]
@reginaldojunior Pattern pra isso acho que não existe, me parece mais um `if` e `else` e nada mais, pois como será verificado depende do que quer verificar, já o que será feito, depende também do que quer ser feito. Mas se ainda sim quer usar algo com nome, dá pra usar um *Pattern matching*, essa gem faz isso: https://github.com/jdantonio/functional-ruby , no final é um switch de forma declarativa.

Já se quiser verificar serviço, seria uma idéia de helth check, que essa gem faz bem: https://github.com/ianheggie/health_check

**Comment by jonasporto** [comment]
Esse serviço está disponível de acordo com alguma configuração? se sim tem o **Feature Toggle** 

- https://martinfowler.com/bliki/FeatureToggle.html 
- https://martinfowler.com/articles/feature-toggles.html

Caso seja você(seu código) quem verifique se o serviço está ativo ou não, você pode usar como inspiração o **Service Discovery**/ **Service Registry**

**Comment by wmartins** [comment]
@reginaldojunior, não sei qual o contexto que tu tá trabalhando (se é com microservices, por exemplo). Mas acho que, como tu mesmo comentou, é legal isolar esse tipo de coisa do código.

Tu pode usar alguma ferramenta pra isso. O trade off é que tu vai ter mais uma ferramenta na tua stack, mas ao menos tu isola o código. Alguns exemplos:

- [**Nginx**](https://www.nginx.com/) - com alguma config pra fazer o **healthcheck** dos serviços pra ti
- [**Linkerd**](https://linkerd.io/) - especificamente utilizando a feature de [Circuit Breaking](https://linkerd.io/features/circuit-breaking/)

Se fizer mais sentido fazer em código, acho que faz sentido isolar essa lógica em algum lugar, e aí o teu código "de negócio" fica isolado disso.
