### ISSUE TITLE
Debug PHP para iniciante

### ISSUE THREAD

**Issue by didiraja** [backend-br/forum#66]
Olá amigos, conheci o repositório pelo FrontEndBR. Embora meu foco seja front-end, eu me interesso um pouco pela parte prática de back (sistemas, envio de email, API) e preciso resolver alguns problemas no trabalho relacionado a isso, principalmente em php.

Apesar do interesse meu maior problema é a hora de debugar. Estou acostumado com JS que tudo que dá errado, ele já avisa no console. Em PHP, as coisas simplesmente não acontecem e dado meu conhecimento limitado, já é de imaginar o quanto eu fico perdido. Esses erros inclusive serviriam para eu aprender mais.

**tl;dr** Qual ferramenta eu uso para saber os erros do meu PHP? Para ver problemas com consultas e envios ao banco de dados, é a mesma ou teria alguma outra ferramenta?

**Comment by reginaldojunior** [comment]
Você pode também testar a sintaxe do php através do seguinte comando no terminal.

"php -l file.php"

http://php.net/manual/pt_BR/function.php-check-syntax.php

**Comment by Matheus-de-Souza** [comment]
@didiraja Segue aqui um [tutorialzinho](https://gist.github.com/odan/1abe76d373a9cbb15bed) pra instalar o xdebug com xampp. O XDebug é life-changing, facilita demais a vida para trabalhar com PHP.

**Comment by gerardo-junior** [comment]
[xdebug](http://br.phptherightway.com/#xdebug) e algum error handler, sem framework recomendo ou o do symfony ou o [whoops](https://github.com/filp/whoops) 

e se você quiser usar o xdebug dentro de um container tem esse gist com uma forma de instalar
https://gist.github.com/gerardo-junior/55721cb1187378b7163b2b269054fc73
