### ISSUE TITLE
Revisão de curriculos

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#67]
Pessoal, o que vocês achariam de um repositorio que faz meio que uma revisão no curriculo da galera e a gente vai ajudando para ele melhorar alguns pontos, o que ele pode adicionar, tirar ou estudar para da aquele up no curriculo?

**Comment by reginaldojunior** [comment]
Funcionaria no esquema de issues, alguem abre uma issue, anexa o curriculo pdf, o linkedin e etc... as pessoas falariam o que poderia melhorar nos comentários e etc...

**Comment by woliveiras** [comment]
É uma boa, ein mano!

No Training Center tem uma ideia parecia, da uma olhada: https://github.com/training-center/hiring-center

**Comment by reginaldojunior** [comment]
Boa! Tô pensando aqui como fazer, uma forma fácil de fazer, esse ele é bem mais detalhado, e tem os avaliadores meio que fixo, será que abrir assim para vários devs poderem avaliar o curriculo é uma boa? 

Eu, acho que é, mas fico com medo de vim alguém e acabar meio que atacando o outro e dando feedback bosta e não construtivo.

Mas acho que vou criar o repositório e testar, ver no que da. Estou pensando em um nome.

**Comment by woliveiras** [comment]
Se criar uma cultura legal, atrai o pessoal legal, mano.

Por isso que nos projetos do TC a gente sempre começa com um time limitado e vai expandindo depois até deixar totalmente aberto, porém com moderação cuidando de tudo.

O risco de aparecer um troll é sempre existente, viu... Pode acontecer mesmo depois que tiver tudo rodando da maneira mais bonita. 

Manda brasa nesse trem! :metal: :metal: :metal: :metal:

**Comment by reginaldojunior** [comment]
Feito, quem puder divulgar ou melhorar o projeto estamos ae! 

https://github.com/backend-br/revise-seu-curriculo
