### ISSUE TITLE
Pesquisa sobre a motivação das pessoas com contribuições em comunidades de programação

### ISSUE THREAD

**Issue by woliveiras** [backend-br/forum#68]
Pessoal, estou fazendo uma pesquisa sobre a motivação das pessoas com contribuições em comunidades de programação. Tanto quem participa quanto quem não participa das comunidades, pode responder e irá ajudar muuuuito a melhorar nossos grupos.

https://goo.gl/forms/H6fJ1elWggTPj7K42

**Comment by mpinheir** [comment]
Feito. Boa iniciativa.
