### ISSUE TITLE
Pós graduação como escolher?

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#7]
Estou querendo começar a pós graduação agora, estou pesquisando umas instituições e cursos. Quem ai já fez? Como foi? Se você não fez, não tem vontade? e pq?

**Comment by ThiagoLuizNunes** [comment]
Eu ainda estou na graduação, mas, não tenho vontade de fazer uma pós graduação e sim uma certificação. Acredito que é algo pouco discutido, realmente quase ninguem fala em fazer uma pós em TI.

**Comment by reginaldojunior** [comment]
Eu vejo a pós muito mais para a área docente, não sei como as empresas veem os pós graduados.

**Comment by ThiagoLuizNunes** [comment]
Pois é, eu penso o mesmo. Acredito que pro mercado de trabalho os certificados tenham maior peso.

**Comment by kivervinicius** [comment]
Empresas não dão valor para pós graduações devido a grande defasagem destes conteúdos, mas julgo muito importante se futuramente tem intenção em ser um docente, como este é meu caso já fiz 2 e estou indo para uma preparação para mestrado, no qual a ponto cientifico é muito gratificante, eu recomendo.

**Comment by reginaldojunior** [comment]
@kivervinicius é minha intenção é ir para o docente mesmo em um futuro. Qual foi a que você fez?

**Comment by kivervinicius** [comment]
@reginaldojunior Didática do Ensino Superior (Unic) Sistemas de Informação (Unigran - Dourados) e agora estou pensando em fazer na funiber um mestrado

**Comment by reginaldojunior** [comment]
Legal, estou pensando em engenharia de software ou big data. Com pós graduação já é possivel começar procurar emprego como professor de faculdade, ou precisa ter o mestrado também?

**Comment by khaueviana** [comment]
Eu vi MBA em Gestão Estratégica de Negócios na FIAP, e cara foi muito legal do ponto de vista de aprendizado, contatos e novas áreas de conhecimento.

Em relação a "up na carreira", não rolou HAHA, algo com: Fiz MBA e dobrei meu salário rsrs

Tomei a decisão de fazer na área de administração, porque queria explorar uma área nova, e aprender nos conceitos, ler outro tipo de livro, conhecer uma galera diferente e por ai vai.

Me formei no ano passado, e agora estou querendo fazer uma pós técnica 💃 🤙

**Comment by jonathas** [comment]
As empresas valorizam mais certificação mesmo (até aqui fora do Brasil), porque conheço gente que tem mestrado e ganha o mesmo que eu que tenho só bacharel. Ja ouvi de gente que nem faculdade tem e trabalha de boa como desenvolvedor, né.. então em questão de "up na carreira", acho que não conta tanto mesmo. É mais pra quem quer ser docente, nao pra mercado de trabalho.
