### ISSUE TITLE
Vagas RJ e SP

### ISSUE THREAD

**Issue by tberne** [backend-br/forum#70]
A [Lumis](http://www.lumis.com.br) está com vagas abertas no RJ e em SP. Veja elas [aqui](https://vagas.com.br/lumis)!

**Comment by onhernandes** [comment]
@tberne tranquilo? Cara, nós concentramos vagas pra dev aqui: https://github.com/backend-br/vagas
Pode postar la por favor? Aqui é só pra perguntas e dúvidas da galera.

Valeu! =]

**Comment by tberne** [comment]
Opa...falha minha =/
