### ISSUE TITLE
Projeto open-source para ajudar pessoas com depressão

### ISSUE THREAD

**Issue by hectorgrecco** [backend-br/forum#72]
Pessoal, sou dev Front-End e estou planejando um projeto full open-source com Vue.js com o seguinte propósito:

- Pessoas depressivas contam suas histórias ou mandam alguma mensagem (seja anonimamente ou não), e qualquer pessoa pode respondê-la enviando textos ou frases de ajuda (seja de empatia e afins).

Sei consumir APIs no front-end, porém ainda não tenho conhecimento bacana para construir uma API com suas respectivas validações do zero. Há alguma ferramenta para criação de APIs utilizando PHP ou outra coisa via interface gráfica? Caso não haja, existe alguém por aqui que gostaria de contribuir com o projeto?

**Comment by reginaldojunior** [comment]
Olá @hectorgrecco ideia interresante, se vingar cuidado com o haters só que podem colocar a pessoa ainda mais para baixo. 

Em fim, para criar um backend sem conhecimento em linguagens back você pode utilizar o [firebase](https://firebase.google.com/?hl=pt-br) por exemplo.

Com ele você consegue criar uma api com base de dados e consumir como REST.

**Comment by hectorgrecco** [comment]
@reginaldojunior Sim sim! Veio a dúvida dos haters na minha cabeça também. Pensei em além de ter um filtro de palavras, as respostas terem aprovação de alguém antes da pessoa receber a mensagem, mas dependendo das proporções que o projeto tome, isso ficaria complicado por ser open-source, não sei bem. 
Já tinha dado uma olhada no Firebase e estava pra começar em pensar em estudar, mas agora sim vou dar uma lida nele com mais afinco. Valeu demais! =)

**Comment by VSPPedro** [comment]
Verdade, @reginaldojunior. 

Vejo como um desafio interessante criar uma espécie de algoritmo para barrar esse tipo de hater. Existe já a ideia de Sentiment analysis, já até pensei em estudar o assunto. Talvez com essa técnica dê para filtrar um pouco a quantidade dos comentários desnecessários. 

De resto é a comunidade vigiar e banir esse comportamento.

Mas esse desafio seria pro futuro quando a ferramenta já estiver mais sólida.

Eu topo ajudar no backend.  Entretanto só no próximo mês, to meio enrolado agora.

**Comment by hectorgrecco** [comment]
Show, @VSPPedro!!! Vou só me organizar também pra criar um grupo no Slack, algo assim! Valeu demais! =)

**Comment by fsrocha-dev** [comment]
Apesar de minha especialidade ser com React, estou afim de cooperar também. Pode contar comigo.

**Comment by reginaldojunior** [comment]
Eu consigo ajudar com algumas coisas também mas não consigo ficar 100%.

Sobre o grupo se quiser crio um lá no backendbrasil e vamos nos organizando por lá quem tiver interesse.

**Comment by reginaldojunior** [comment]
Pode criar um MVP da ideia com o firebase e depois o @VSPPedro pode ajudar criando algo mais estável e parrudo.

**Comment by hectorgrecco** [comment]
Criei um grupo no slack, pra quem tiver interesse:
https://join.slack.com/t/projeto-opensource/shared_invite/enQtMzkzOTEzMDA3Mjg2LTc5MGM0YjhjZDA0YjgzNTI1MzJlZTgyMDc1YzA4MWMyNDlkMTczNGIyZDA1NGVkOWMxYTUwMzQ4NGNmMDc4ZjM

**Comment by OtavioHenrique** [comment]
Um sisteminha de blacklist pode ajudar a evitar alguns haters em uma fase inicial tabém

**Comment by jonathas** [comment]
Se vocês estiverem afim de criar uma API com Node.js, TypeScript e Express, posso dar umas dicas e ajuda. Aqui um exemplo de como eu geralmente organizo um projeto: https://github.com/jonathas/todo-api
