### ISSUE TITLE
Bancos de dados relacionais Open Source

### ISSUE THREAD

**Issue by houstondapaz** [backend-br/forum#73]
Estou começando um projeto e preciso usar um bd relacional, mas estou muito tempo só usando BD NoSQL e o ultimo que usei relacional foi o SQL Server, que não temos dinheiro para pagar hahaha

Qual a opinião de vcs sobre os open que temos atualmente (MySQL, PostgresSQL, MariaDB...)?
Quais estão usando, o que acha dele, qual indicaria e pq?

**Comment by delley** [comment]
Eu iria de postgres. Na minha opinião é o mais robusto, mas não tenho conhecimentos técnicos para suportar minha opnião, por isso deixo o seguinte link para você dar uma olhada: [Migração de Oracle para PostgreSQL – Indo além do SGBD](https://www.infoq.com/br/presentations/migracao-de-oracle-para-postgresql-Indo-alem-do-sgbd)

**Comment by wbotelhos** [comment]
Oi @houstondapaz ,

Como está acostumado com o NoSQL, o Postgres, além de ser muito bom em suas funções, dá um suporte bem legal para armazenar JSON. Talvez isso facilite o seu trabalho. Outra coisa que me agrada muito são os conjuntos de extensões que ele possui.

**Comment by houstondapaz** [comment]
@delley a palestra da migração é bem interessante, para um banco aguentar uma carga dessas ele tem que ser bem parrudo msm.

@wbotelhos a minha ideia é não armazenar JSON, se for fazer isso eu uso um NoSQL em paralelo, eu ainda não tenho nenhum parametro para escolher entre o Postgress e os outros.

**Comment by mahenrique94** [comment]
Sempre utilizo MySQL ou PostgreSQL, porém, a diferença eu eu faço seria no tamanho do projeto e necessidade:

- MySQL: Para projetos mais simples, onde preciso de mais velocidade e algo não tão parrudo.
- PostgreSQL: Para projetos de maior porte, onde preciso de toda uma necessidade maior.
