### ISSUE TITLE
Manter processos do Python executando em produção

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#75]
Eu tô aprendendo Python e to querendo colocar um projeto no ar. O projeto tem 2 scripts que servem como `workers` e outro como API com o Flask.

Tem alguma maneira que eu poderia deixar eles em execução? Com esquema de logs e etc.

Dei uma olhada e vi algumas coisas pra ligar o Flask com NGINX, por exemplo, e também pensei em usar o `supervisor` pra manter os workers de pé. Mas queria saber se há outras maneiras melhores/mais seguras/comuns de se fazer isso em produção.

**Comment by onhernandes** [comment]
@rafa-acioly 

No caso do Flask, tem algo que eu possa usar pra salvar os logs, e garantir que o processo não morra?

Como no PHP, tem a ligação com o Apache pra executar/manter a aplicação rodando e tals, teria algo pro Python?

Ou algo como o pm2 do nodejs.

E esse do `while true:` não é meio gambiarra? É seguro usar em produção? 

Não vai me dizer que tem projeto no ar com isso cara HAHAHAHAHAHHAHAHA

**Comment by rafa-acioly** [comment]
@onhernandes 

Como você fazendo para gerar `logs`?

Não conhecia esse `pm2` do node, bem bacana! :)
com relação a python não sei se existe algo parecido.

> O apache não mantém nada rodando (até onde eu saiba), ele simplesmente executa um arquivo quando você acessa uma determinada `URL`.

> E esse do while true: não é meio gambiarra? É seguro usar em produção?
não é gambiarra e se é seguro depende de como você faz, só se certifique de salvar logs, colocar um delay entre o loop e etc. O simples é sempre o melhor a se fazer.
Quando se cria arquivos assim é sempre bom ter algumas coisas a disposição, como por exemplo um `healthcheck` que te diz quando tempo esta levando para cada iteração, se o processo ainda esta vivo e etc, tudo isso você consegue fazer só com `python` e usando recursos do `unix`.

**Comment by jonathas** [comment]
while true é muita gambiarra :smile: 

Na epoca em que eu estava pesquisando sobre python em produção, vi um container com uWSGI e Nginx (apesar de achar que o Nginx tem q ficar em um container separado) https://hub.docker.com/r/tiangolo/uwsgi-nginx-flask/

Tem também o Phusion Passenger que você pode usar:
https://www.phusionpassenger.com/features
https://github.com/phusion/passenger

ou você pode manter o processo de pé até com o systemd, caso seu OS use isso e vc preferir não usar Docker.

sobre logs, nos sistemas que eu desenvolvo tenho utilizado o https://sentry.io

**Comment by rafa-acioly** [comment]
Tem o `gunicorn` também;

https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-14-04

falei sobre o `while true:` porque não sei o tamanho do seu worker ou se é um projeto pessoal ou pra firma 😃 
na duvida vai de supervisor mesmo.

**Comment by onhernandes** [comment]
O projeto é pessoal mas queria subir a API e montar um site pra mostrar as coisas. Ainda essa semana tá no ar e eu posto aqui o link.

@rafa-acioly eu tenho um `for` que consome uma função que puxa da API, e essa função é um generator, eu coloquei um `time.sleep()` lá pra ajudar hahahahah, mas o `while true:` seria o mesmo praticamente.

Vou dar uma olhada no `gunicorn`. Eu estava querendo seguir com https://docs.python-guide.org/writing/logging/ pra logs

@jonathas curti o Phusion, vou brincar com ele mais tarde. Pensei sobre o Docker também, mas não tem muita coisa ligada ao ambiente além do Python puro ausdhuad, talvez use mais pra frente pra praticar e aprender melhor.

Não tinha visto sobre o Sentry, achei bem interessante por ser integrado direto com o Flask já. Vou testar também.

Valeu galera!

**Comment by rafaelpaixao** [comment]
Mas porque não usar o supervisor?
Eu vejo como uma aplicação confiável, fácil de usar e fácil de monitorar.

Caso seja um projeto que requer escala, considerou utilizar o celery?
