### ISSUE TITLE
Dicas de segurança para servidores

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#76]
Comprei uma instância de um servidor no [Vultr](https://www.vultr.com/) e estou configurando algumas coisas, principalmente pra melhorar a segurança do servidor. 

Quais coisas vocês acham necessárias para aumentar a segurança do servidor?

Coisas como fechar portas que não estão sendo usadas, usar apenas SSH, trocar portas padrões, etc.

**Comment by JonatanLima** [comment]
Acho interessante você usar proxy reverso pra conectar frontend, com backend, faço isso bastante quando uso Docker.

**Comment by kivervinicius** [comment]
geralmente tranca-se todas as portas com excessão da 80 e 443 e todo fluxo de outras aplicações são gerenciado por um proxy reverson como o @JonatanLima falou, te indico o NGINX que possui uma forma muito simples de fazer essas configurações, instale um antivirus (ClamAV) e utilize docker em aplicações (caso de algum problema o rollback é fácil e limpo), faça sempre o monitoramento de seu servidor de forma automatizada (NewRelic ou Zabbix).

**Comment by jonathas** [comment]
Acho interessante também desabilitar ssh por root e desabilitar ssh por password, usando só public key

**Comment by OtavioHenrique** [comment]
VPN também pode ser bem legal
