### ISSUE TITLE
Mestrado em engenharia de software - Dicas, ajuda e por onde começar

### ISSUE THREAD

**Issue by reginaldojunior** [backend-br/forum#78]
Já sei que tem um pessoal aqui que fez mestrado e etc...

Quero saber onde fizeram, quais passos seguiram para começar fazer o mestrado.

Meu foco é para pesquisa e lecionar, qual caminho devo seguir, o que estudar, onde fazer?

Queria começar no próximo ano já...

**Comment by henriquegibi** [comment]
Boa tarde.

Entendo que seja uma _issue_ de 2018, mas eu realmente gostaria de aclarar que mestrado tem um peso maior para quem deseja dar aulas e seguir com a vida acadêmica, pelo menos no Brasil.

Se a meta for o mercado de trabalho, um MBA lhe daria o necessário para possuir uma mão de obra desejada. Mas se o _goal_ for a vida acadêmica, você está no caminho certo.
