### ISSUE TITLE
Dicas para inciantes na área

### ISSUE THREAD

**Issue by brenoma** [backend-br/forum#79]
Bom, como dito, sou iniciante na área, há uns 4 anos eu iniciei um curso superior de ciências da computação, porém mudei de curso por diversos fatores... mas o que acontece é que eu voltei esse semestre (estou no 3º período da faculdade) e queria saber quais são as dicas para vocês para eu conseguir experiência com o conhecimento que já possuo, pois eu vejo que não há muita oportunidade, ou estou procurando em lugares errados, pois todo estágio pede experiência. 

Conhecimentos:
- Java
- Python
- C
- Ruby
- Assembly Mips

**Comment by JonatanLima** [comment]
Boa noite Breno, realmente na procura do primeiro estágio é difícil, mas
não desista.
Em relação aos conhecimentos, você tem conhecimentos legais, mas primeiro
você deve procurar se identificar, web, backend, frontend, machine
learning, big data.
Definindo sua área de atuação você escolhe a linguagem com a qual você mais
se identifica.

Tem bastante opções, por exemplo pra web com Python tem o Django, Flask,
pra Ruby tem Ruby on Rails.


 Jonatan dos Santos Lima

 Full Stack Developer and Web Designer



  Celular: 21 96871 7690

  https://jonatanlima.com/



Em qui, 13 de set de 2018 às 17:20, Breno Menezes <notifications@github.com>
escreveu:

**Comment by reginaldojunior** [comment]
Geralmente o que pedem no estágio são experiências em projetos próprios.

Acho que vale a pena, você pega uma linguagem que mais se identifica e construir um projeto do 0 com ela para adquirir experiência necessária de passar pelos problemas de construir algo.

Assim, você já tem argumentos do que falar nas entrevistas e colocar no curriculo, procura da uma investida de tempo em meetups e comunidades especificas de linguagem. Pode ajudar você também, tanto em networking quanto experiência.

Para finalizar, indico esse episódio de podcast:

http://quebradev.com.br/iniciando-no-desenvolvimento-web-back-end/

Uma visão geral de como começar na área, espero que as dicas ajudem e se tiver mais algo fala com a gente.

**Comment by BrunoGianetti** [comment]
Tenho uma situação parecida com a do @brenoma. Tenho uma formação técnica dos idos de 2000 e depois fiz uma graduação noutra área completamente diferente e fui estudar pra Polícia Federal e Receita Federal. Após os concursos evaporarem, decidi voltar pro código, tirar minha cidadania italiana e sair do país.

Nesse meio tempo reiniciei os estudos de linguagens e fui construindo algumas ideias (elas estão lá no meu repositório - https://github.com/BrunoGianetti?tab=repositories).

Ocorre que recentemente me deparei com esse material aqui: https://roadmap.sh/backend

Achei ele bem robusto e objetivo. Acabei vendo ele sendo referenciado por devs espalhados pelo globo.

Atualmente esse roadmap é meu norte. Tô buscando material de estudos e cumprindo seus tópicos. Está sendo bem produtivo.

E, claro, atirando em peso nas vagas.

**Comment by brenoma** [comment]
Galera, depois de muitos anos... Eu consegui uma vaga pra Trainee naquela época, consegui outro trabalho como Júnior, me identifiquei mais com a área de desenvolvimento Backend com Java e algumas práticas de DevOps. 🤜🏽🤛🏻

**Comment by reginaldojuniorcreditas** [comment]
@brenoma que coisa boa de ser ler logo nessa semana de natal e ano novo. Isso mostra que o foco e disciplina e com a comunidade podemos conseguir, fico feliz de você ter conseguindo um emprego na área e ter se identificado com backend. Espero que colha muitos frutos que você está plantando e ajude pessoas na caminhada para também entrar na área ou trocar conhecimentos. Sucesso!
