### ISSUE TITLE
Fluxo de trabalho com o banco de dados - Migration EF

### ISSUE THREAD

**Issue by carloshenriqueribeiro** [backend-br/forum#80]
### Galera, boa noite!

**Objetivo:** Benchmarking com a comunidade sobre o tema: _fluxo de trabalho com o banco de dados_.

**Stack :** .NET Framework, code first, EF com Migration, Rest API.

**Cenário :** um time com 3 desenvolvedores trabalhando no mesmo repositório (back-end - Rest API) e não gostaria de trabalhar com banco de dados local, ou seja, na máquina dos Devs.

**Qual a dor ?**
Sempre que um dos devs faz um "update-database" ele tem que comitar, dar push e avisar aos outros devs que eles não vão conseguir rodar o projeto localmente enquanto não pegarem a última versão do Migration.

**Como vocês trabalham ?** 

- Criam um repositório separado para o versionamento do banco de dados ?
- Trabalham com o AutomaticMigrationsEnabled = true, ou seja, migration no automático ?

Alguma sugestão para melhorar o fluxo de trabalho ?

**mesmo se trabalhar com outra stack, conte um pouco sobre o seu cenário.**

_leituras auxiliares que encontrei_
https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/teams
https://stackoverflow.com/questions/13314725/migrations-in-entity-framework-in-a-collaborative-environment
http://www.entityframeworktutorial.net/code-first/automated-migration-in-code-first.aspx

**Comment by ismaelgasparin** [comment]
O grande problema de usar migrations por mais de um dev, é que se o dev1 adicionar uma migration1 e o dev2 adicionar uma migration2, cada qual em branch separados, no momento do merge, um deles vai ficar com uma migration "perdida".

No projeto que estou trabalhando, a base de dados é criada pelo time de dbas, então, rodamos o scaffold num projeto separado e vamos inserindo os mapeamentos que queremos no nosso projeto. Não temos migrations pelo EF, e sim, o time de dbas que faz e controla as versões do banco de dados. O único empecilho é depender deles para alterações de schema e depender de scripts para criar uma nova base de teste.

Se não fosse dessa forma, criaríamos um projeto separado só para criar dos mapeamentos e migrations do banco de dados. Mas, mesmo assim, caso os devs criassem migrations cada qual no seu pc, no momento do merge, iria dar problema em um deles.

Há um tempo havia procurado sobre como gerenciar versões do banco de dados, e vi sobre usar uma outra ferramenta para criar essas migrations. Infelizmente, não lembro qual era a ferramenta :(
