### ISSUE TITLE
Hospedagem

### ISSUE THREAD

**Issue by onhernandes** [backend-br/forum#87]
Opa galera, o que cês usam pra hospedar projetos seus? Seja pessoal, freelas, etc

Atualmente eu tenho duas máquinas no Vultr - uma de proxy e outra com projetos mesmo.

**Comment by AlbericoD** [comment]
aws ou google cloud

**Comment by brazica** [comment]
heroku

**Comment by lucassantos61** [comment]
Atualmente eu tenho usado heroku , mas tbm tenho cogitado Amazon (mas estou achando um pouco caro)

**Comment by kivervinicius** [comment]
Digital Ocean

**Comment by OtavioHenrique** [comment]
Aws mesmo, usando o AWS Elastic Beanstalk da para subir a maioria dos serviços rápidos, você instala a CLI, configura e tipo de projeto e faz deploy, ele tem suporte para Python/Ruby/PHP/Node/Java/.NET. Os custos você paga o que usar (instancias ec2, banco rds etc..)

Para sites estáticos tem o próprio S3. 

https://aws.amazon.com/pt/elasticbeanstalk/

**Comment by jass2125** [comment]
O Heroku resolve bem meus problemas.

**Comment by TiagoDanin** [comment]
GitHub Pages - Apenas HTML estático.
Heroku - Tudo que é Open Source e tem site.
NOW - Apenas para projetos de testes.
Azure - Projetos que não tem website (maioria são bots para Telegram).

**Comment by isacmoura** [comment]
Tenho usado o Heroku. Vem me servindo bem quando é pra hospedar a aplicação.

**Comment by neiesc** [comment]
https://www.linode.com
https://www.digitalocean.com/
https://www.hetzner.com/ (DE)

**Comment by jeancsanchez** [comment]
Heroku
