### ISSUE TITLE
Seria a divisão entre frontend e backend um antipattern?

### ISSUE THREAD

**Issue by woliveiras** [backend-br/forum#88]
Galera, li um artigo interessante e gostaria de ouvir (ler, no caso) a opinião de vocês sobre isso.

Eu tenho uma opinião formada, mas não quero enviesar sua resposta, então comenta ae o que pensa sobre esse assunto:

[Dividing frontend from backend is an antipattern](https://www.thoughtworks.com/insights/blog/dividing-frontend-backend-antipattern)

> P.S.: muito provavelmente o autor não quis ofender ninguém com seu texto

**Comment by jonathas** [comment]
Eu já concordo com esse comentário que deixaram lá:

Martin Nowosad • 2 months ago
Frontend and Backend are actually two different things and they have to solve different problems.
A Backend developer has to design his system under different circumstances than a Frontend developer. While a Frontend Developer needs to take care of a good UI & UX design a backend developer needs to make sure the everything is still working with several thousand users per second. While a monolith architecture will work for almost all frontend projects, it will not for many backend systems that face heavy load which causes another challenge that a frontend dev will never have.
There are many more comparizitions to illustrate that backend and frontend devs do different things and have to face different challenges.
Not dividing between frontend and backend developers would be an anti-pattern and a potential problem for many companies

**Comment by klarkc** [comment]
TL;DR
Não falo contra a especialização em geral, mas contra à noção de que existem apenas back/front e que sempre deve ser assim em todos os cenários.

Não acho q seja um anti-pattern, cada caso precisa ser analisado sob a ótica do problema em questão. Dito isso, ocorre que muitas vezes toma-se por verdade absoluta que todos os sistemas devem ser divididos entre backend / frontend, isso começa nos desenvolvedores e cresce pra times de "back" e times de "front", isso é sim, pode ser considerado algo bastante prejudicial, pois limita a capacidade de inovação dentro dos times por falta de comunicação e interação.

Sistemas ricos e complexos que resolvem problemas desafiadores podem ser criados quando nos livramos do estigma de que back cuida do banco e da performance e que front cuida da pele. Times multidisciplinares, com especialistas de todas as áreas tendem a construir soluções mais eficientes e com maior qualidade final.

Backenders devem entender que gaps de performance não começam quando o endpoint está cheio de requisições que precisam ser otimizadas, mas que a performance tem de ser levada em consideração na ideação do produto, na validação dos protótipos e na escolha de arquitetura do front.

Frontenders devem entender que a participação do backend é de suma importância para viabilidade da solução, uma vez que a presença de um especialista antecipa problemas que por vezes mudam a solução no front.

O mundo de TI é muito amplo para se encaixar a divisão backend/frontend como um formato que demanda as duas especializações. Hoje temos cientista de dados, gestores de banco de dados, devops, ux/ui designers, desenvolvedores mobile, e por aí vai.

Deve-se sempre pensar na solução como um todo, partindo disso, decidir se a divisão clássica entre back/front faz sentido.
