### ISSUE TITLE
Existe diferença entre "Developer" e "Engineer"?

### ISSUE THREAD

**Issue by kaiofelipejs** [backend-br/forum#89]
Galera, vejo que um novo nome foi surgindo ao longo do tempo nas vagas (tanto back quanto front) para pessoas desenvolvedoras, o nome de **Engineer**. Conversando com algumas pessoas, já ouvi casos de que a pessoa engenheira era considerada "pós sênior" (exemplo: dev junior, dev pleno, dev senior, engenheira(o)).

Qual a opinião de vocês quanto a isso? Existe realmente uma diferença nesses papeis de _Developer_ e _Engineer_? Vocês deixam de se aplicar para vagas que tenham nomes diferentes?

Teve uma discussão parecida assim no forum do frontendbr e foi bem proveitosa [(link aqui)](https://github.com/frontendbr/forum/issues/32). Além disso, o [DNE](https://devnaestrada.com.br/) no episódio [#206](https://devnaestrada.com.br/2019/05/17/especialista-fullstack.html) fala um pouco sobre isso também.

[]'s

**Comment by NicholasKuchiniski** [comment]
IMO acredito que sim, existe, e um engenheiro de software não é a mesma coisa que um desenvolvedor. O engenheiro deveria ser capaz de participar  ou no mínimo ter conhecimento do processo de construção do software como um todo, tem gente que se diz "software engineer" e nunca se preocupou em aprender algo além da parte do código. Hoje em dia teve uma banalização do termo, as empresas lá fora costumam se referir aos times de tecnologia como "Engineering" e acho que o pessoal pegou isso e ta usando para qualquer um que trabalhe com programação ou tecnologia, exemplo é UX Engineer, coisas do tipo. Acho que as pessoas utilizam isso muito mais como um açucar a mais no título do que para específicar algo que elas realmente fazem.

Imagino que o termo correto seja Desenvolvedor de Software _(Software Developer_) ou simplesmente Desenvolvedor (que já é associado automaticamente a software 😄 ), mas no final, ninguém ta ligando para isso mesmo.

Devido a utilização do termo de forma errada, não tem sentido deixar de se aplicar para uma vaga só porque ela pede software engineer no nome.

**Comment by gustavomtborges** [comment]
Na teoria existe diferença sim, na prática você escolhe o nome que mais te agrada e usa. Eu mesmo sou formado em Engenharia de Software, mas prefiro colocar no CV e afins Desenvolvedor de Software porque retrata melhor minha função. Em relação a vagas eu vejo mais os requisitos do que o título.

**Comment by mdamaceno** [comment]
Me parece que é só no Brasil que tem essa diferença. Eu entendo que é tudo a mesma coisa.

**Comment by sfiorotti** [comment]
Não tem diferença nenhuma pra mim!
