### ISSUE TITLE
Mapeamento de um Banco de dados SQL Server a partir de um diagrama, com EF Core.

### ISSUE THREAD

**Issue by PabloFerreiraB** [backend-br/forum#91]
Tenho um diagrama de um banco, onde criei um projeto asp.net core e estou utilizando code first.
Estou com muitas dificuldades em realizar o relacionamento/mapeamento desse banco.

Podem me esclarecer algumas coisas, ou até mesmo me ensinar a maneira correta para fazer isso.
Posso dar mais detalhes caso alguém se propor à me ajudar. Obrigado!

**Comment by reginaldojunior** [comment]
Olá @PabloFerreiraB coloca melhor qual o problema com os exemplos que voce tiver para tentamos ajudar.

**Comment by PabloFerreiraB** [comment]
Não tive seguimento mais com o projeto, por isso estou fechando a issue.
