### ISSUE TITLE
Alguém para me ajudar com relacionamentos no SQL Server 2017.

### ISSUE THREAD

**Issue by PabloFerreiraB** [backend-br/forum#92]
Preciso de um explicação sobre como relacionar tabelas no sql server, pois criei meu banco e relacionei as tabelas, porém me parece incorreto. Mas como não tenho certeza, preciso de ajuda. Segue foto da tela com os campos, depois a imagem do relacionamento no sql server e por fim a forma que o EF Core relacionou pra mim na minha aplicação. Obrigado!
![image](https://user-images.githubusercontent.com/23368724/61344627-4ae21700-a828-11e9-8dc4-dc0275f2a19b.png)
![image](https://user-images.githubusercontent.com/23368724/61344636-559cac00-a828-11e9-876f-bb210c55dbce.png)
![image](https://user-images.githubusercontent.com/23368724/61344664-6d743000-a828-11e9-87fa-092a21203095.png)

**Comment by jeancsanchez** [comment]
Eu faria algo mais ou menos assim:

`Grupo`
    - cod
    - nome

`Item`
    - cod
    - descricao
    - `grupo` (HasOne)

`Pedido`
    - cod
    - `item` (HasOne)
    - observacoes

`Estoque`
    - cod
    - item (HasMany)
    - estoqueAtual
    - estoqueMin
    - valorUni
    - ativo

**Comment by neiesc** [comment]
conseguiu resolver @PabloFerreiraB ?
