### ISSUE TITLE
Como contribuir com um erro resolvido?

### ISSUE THREAD

**Issue by felipe-b-oliveira** [backend-br/forum#94]
Estou começando na área, fazendo um exercício da Udemy, encontrei um erro, consegui resolver com ajuda do pessoal aqui do trabalho e gostaria de contribuir de alguma forma, não achei muita coisa na internet sobre o erro em questão.

Linguagem: C# / .NET Core
IDE: Visual Studio Code
Erro: System.NullReferenceException

O erro ocorreu dentro de uma linha vazia em um método, após acompanhar o debug e revisar o código, tive que refazer a build do projeto para que o erro se resolvesse.

**Comment by reginaldojunior** [comment]
Olá. em qual projeto o erro está ocorrendo?

**Comment by felipe-b-oliveira** [comment]
Em um projeto/exercício em que eu estava fazendo de um curso online. Consegui resolver o erro, gostaria de saber se tem algum local específico para caso alguém passe pelo mesmo tentar resolver.

Fiquei travado nesse erro durante alguns dias e não era erro do código, após refazer a build o programa voltou a funcionar.

Eu tenho tido algumas dificuldades com o .NET Core no Ubuntu.

**Comment by felipemfp** [comment]
Você pode descrever a dúvida/problema no StackOverflow. E como você já resolveu, você mesmo escreve a resolução. Assim fica documentado e caso algo tenha o mesmo problema.

Aproveita e deixa um comentário no curso que você tá fazendo na Udemy se tiver algum canal de fórum.
