### ISSUE TITLE
qual a base para começar um projeto?

### ISSUE THREAD

**Issue by camila1467** [backend-br/forum#96]
bom. Minha duvida é bem simples. Eu to começando na área e estudando desenvolvimento, porem, vejo muitas pessoas dizendo sobre fazer projetos.. eu entro aqui e vejo muita coisa que não entendo,sei que é uma vasta área e tem muuuita coisa pra se aprender. Quando dizem "faça projetos pra iniciar" no que se referem?

**Comment by danilozagatto** [comment]
Oi Camila, quando as pessoas se referem fazer projetos para iniciar, é começar do zero criando algo, por exemplo: criar um pequeno sistema de gerenciamento de notas escolares, ou um sistema para supermercados. O objetivo para quem estar começando é começar a se familiarizar com os conceitos de desenvolvimento, os conceitos de Orientação a Objetos, como funciona um Git, um deploy etc., pense que: o objetivo é te aproximar o máximo possível de um projeto real

**Comment by JonatanLima** [comment]
Olá Camila, comece com um CRUD (CREATE, READ, UPDATE, DELETE) básico, pode ser um sistema de cadastro de produtos, depois comece a estudar protocolo http e entender sobre Request e Response, Boas práticas de desenvolvimento, como MVC (MODEL, VIEW, CONTROLLER), modelagem de bancos e dados e vá evoluindo gradualmente.

**Comment by jq2** [comment]
> Quando dizem "faça projetos pra iniciar" no que se referem?
"Escreva código !!!", "mãos à obra !!!". 

É normal que, ao iniciar uma carreira em programação de computadores, você crie alguns projetos que vão fracassar, ou seja, projetos que não serão bem-sucedidos, mas vão iluminar seu caminho para progredir e aprender com seus erros.

Então, somente com o tempo (teoria + prática) você ganhará experiência.

Abraços!, e qualquer dúvida, entre em contato comigo.

Att, @jq2.

**Comment by camila1467** [comment]
@jq2 ai esta, nesse ponro. QUE projeto?O que fazer, por exemplo, eu aprendi a programar em c o básico, ode aplico tais conhecimentos? Tanto em c, quanto em outras linguagens, a faculdade somente ensina mas não mostra pra que serve

**Comment by PresHam** [comment]
> Olá Camila, comece com um CRUD (CREATE, READ, UPDATE, DELETE) básico, pode ser um sistema de cadastro de produtos, depois comece a estudar protocolo http e entender sobre Request e Response, Boas práticas de desenvolvimento, como MVC (MODEL, VIEW, CONTROLLER), modelagem de bancos de dados e vá evoluindo gradualmente.

@camila1467, essa é a melhor dica que você pode receber, meu primeiro projeto(ano passado) foi criar um webscrapper (tem como objetivo extrair informações de páginas na internet) que diariamente coletava informações do climatempo no site do g1 e armazenava em um banco de dados para o qual criei meu primeiro CRUD (create, read, update e delete. Operações básicas de banco de dados).

Não vi utilidade para esse projeto, mas para aprender algumas coisas legais selecionei para o projeto:
Python3, os framworks Selenium, Flask, Django e o banco de dados MongoDB.

Detalhe, apesar de saber lógica de programação e algum conhecimento em Java e Javascript, aprendi Python do zero e desenvolvi muitas habilidades e práticas novas. Espero que você alcance seus objetivos, ninguem começa sabendo!

**Comment by mstuttgart** [comment]
@camila1467 uma sugestão que eu te daria é manter a simplicidade e ir com calma. No fórum, temos pessoas de vários níveis técnicos e tempos de experiência, então as vezes a discussão de um determinado assunto pode te parecer complicado, mas é algo que com o tempo você vai eventualmente entender. 

Você comentou a respeito de aprender C na faculdade e eu te entendo porque eu já me senti do mesmo jeito. Realmente as vezes o tempo para passar os conceitos das linguagens é curto, então o ensino carece de exemplos práticos. A ideia é que você aprenda BEM o conceito de lógica de programação e também estude por si mesma. Com o tempo, você adquiri experiência e consegue ver diversos locais onde você pode aplicar o que aprendeu, bem como alguns conceitos começam a ficar mais claros.

No caso do C, por exemplo dá pra fazer muita coisa (muita coisa mesmo...), desde de jogos, "programa de padaria", sistema embarcados até sistemas operacionais :) 

Então a sugestão que te dou (no caso do C, por exemplo) é o caminho que eu segui. Lembrando que estou considerando que você esta começando a aprender a linguagem.

* Comece criando pequeno jogos em C (xadrez, dama, jogo da velha, jogo da memória) apenas usando o terminal/console, apenas com texto (criar interface gráfica - janelas para a sua aplicação - pode acabar atrapalhando bastante você no começo). Jogos são ótimos para treinar lógica de programação e normalmente são multidisciplinares. Se você fez um jogo da velha, por exemplo, tente em seguida, desenvolver um modo de você jogar contra o computador (o computador pode fazer jogadas aleatórias ou a melhor jogada, dependendo da dificuldade). Adicionar possibilidade de jogar com dois jogadores (no mesmo computador/teclado no caso, jogar em rede é um pouco mais avançado).

* Criar um aplicativo para cadastro de notas escolares (novamente, funcionando apenas com texto no terminal), que salva os dados cadastrados em um arquivo de texto e que permite carregar as notas de um arquivo de texto já existente (uma versão super simples do CRUD que o pessoal comentou). Isso vai te dar um base sobre leitura de arquivo em disco e bastante aprendizado.

* Procurar alguma tarefa que você faz repetidamente e tentar automatizar ela. Por exemplo, pegar todas as imagens que estão na pasta Download e mover para a pasta Imagens. Fazer o mesmo com os arquivos de vídeos (dá pra pesquisar pela extensão do arquivo). 

* Para cada um dos mini projetos, crie um repositório no Github e sempre envie as modificações que fizer no código, isso vai te ajudar bastante a se familiarizar com git e com o Github, que é algo que o pessoal hoje em dia usa muito (e que a faculdade não vai te ensinar)!

Esses são alguns pequenos exemplos que usei no começo da faculdade pra estudar, mas que me ajudaram muito a fixar determinados conceitos. Mas deixo a sugestão de começar com coisas bem simples e se preocupar mais em aprender os conceitos de lógica de programação que é algo que você vai usar em toda a sua carreira. Como nosso amigo @PresHam sabiamente comentou, ninguém nasce sabendo, então vá com calma e tente ir desenvolvendo pequenos projetos como os do exemplo que passei usando o que você sabe e boa sorte com os estudos!
