### ISSUE TITLE
Esse curso é bom e/ou vale a pena?

### ISSUE THREAD

**Issue by eD0o** [backend-br/forum#97]
https://www.pucsp.br/graduacao/ciencia-de-dados-e-inteligencia-artificial#curso

Curso: ciência de dados e inteligência artificial
Faculdade: PUC-SP Campus Monte Alegre

É um curso novo, pode ter tudo pra ser promissor, ou não... O que vocês acham?

A grade pra quem não quer abrir o link:

1 | Consultoria Especializada de Apoio ao Projeto Integrado: Matemática (Funções e Discreta) | 72
-- | -- | --
Consultoria Especializada de Apoio ao Projeto Integrado: Algoritmos e Programação | 36
Introdução ao Pensamento Teológico | 54
Estudos Orientados | 72
Projeto Integrado: Aquisição e Visualização de Dados | 72
2 | Consultoria Especializada de Apoio ao Projeto Integrado: Probabilidade e Estatística | 72
Consultoria Especializada de Apoio ao Projeto Integrado: Estrutura de Dados e Programação | 36
Teologia em Diálogo com as Tecnociências | 54
Estudos Orientados | 72
Projeto Integrado: Aquisição e Visualização de Dados | 72
3 | Consultoria Especializada de Apoio ao Projeto Integrado: Probabilidade e Estatística | 72
Consultoria Especializada de Apoio ao Projeto Integrado: Otimização e Simulação | 36
Consultoria Especializada de Apoio ao Projeto Integrado: Bancos de dados (SQL e NoSQL) | 36
Estudos Orientados | 72
Projeto Integrado: Negócios (Logística, Finanças, Crédito, Engenharia etc.)) | 108
4 | Consultoria Especializada de Apoio ao Projeto Integrado: Mineração de Dados | 72
Orientação profissional | 36
Governança de Algoritmos | 36
Projeto Integrado: Redes Sociais e Marketing | 108
5 | Consultoria Especializada de Apoio ao Projeto Integrado: Aprendizagem de Máquina | 72
Consultoria Especializada de Apoio ao Projeto Integrado: Sistemas Distribuídos | 36
Projeto Integrado: Segurança Cibernética e Engenharia Social | 108
6 | Consultoria Especializada em Ciência de Dados 1: Eletiva | 36
Consultoria Especializada em Inteligência Artificial 1: Eletiva | 36
Optativa da Universidade | 54
Trabalho de Conclusão de Curso 1 | 108
7 | Consultoria Especializada em Ciência de Dados 2: Eletiva | 36
Consultoria Especializada em Inteligência Artificial 2: Eletiva | 36
Optativa da Universidade | 54
Trabalho de Conclusão de Curso 2 | 108

**Comment by eD0o** [comment]
Tentei fechar a issue porque a parte dos números 1,2,3,4,5,6,7 bugaram, o que parecem ser títulos dos semestres são só disciplinas

**Comment by lucassantos61** [comment]
E ai tudo bem @eD0o , então eu dei uma lida na emenda do curso parece bacana, mas antes de perguntar para a gente se o curso vale a pena vc tem que inserir ele no seu contexto e imaginar se ele vai ser bom para vc, por que vc tem que levar em conta se é algo que vc realmente quer fazer, pois vai ter um investimento financeiro e de tempo de estudo. Seria bacana perguntar para o pessoal que já fez o curso para ver o que eles acharam e como foi procurar um emprego depois de fazer o curso.
